import type { Recipe } from "./Recipe";

// Helper function to generate sample reviews
// This function is kept for future use when generating dynamic sample data
// eslint-disable-next-line @typescript-eslint/no-unused-vars
const generateSampleReviews = (count: number, averageRating: number) => {
	const reviews = [];
	const userNames = [
		"Alex",
		"Jamie",
		"Taylor",
		"Jordan",
		"Casey",
		"Riley",
		"Morgan",
		"Sam",
		"Quinn",
		"Avery",
	];
	const comments = [
		"Absolutely loved this recipe! Will definitely make it again.",
		"Great flavors, but I added a bit more spice to suit my taste.",
		"Easy to make and delicious. My whole family enjoyed it.",
		"Perfect for a weeknight dinner. Quick and tasty!",
		"The instructions were clear and it turned out perfectly.",
		"Good recipe but took longer to prepare than stated.",
		"Healthy and flavorful - a new favorite in our house!",
		"I substituted a few ingredients and it still turned out great.",
		"Not my favorite, but still pretty good.",
		"Amazing recipe! The flavors were perfectly balanced.",
	];

	for (let i = 0; i < count; i++) {
		const rating = Math.max(
			1,
			Math.min(5, Math.round(averageRating + (Math.random() * 2 - 1))),
		);
		const randomDate = new Date();
		randomDate.setDate(randomDate.getDate() - Math.floor(Math.random() * 60));

		reviews.push({
			id: `review-${i + 1}`,
			userId: `user-${i + 1}`,
			userName: userNames[Math.floor(Math.random() * userNames.length)],
			rating,
			comment: comments[Math.floor(Math.random() * comments.length)],
			date: randomDate.toISOString().split("T")[0],
		});
	}

	return reviews;
};

export const sampleRecipes: Recipe[] =
	// [
	// 	{
	// 		id: "1",
	// 		name: "Marry Me Chickn with Soy strips",
	// 		description:
	// 			"A delicious plant-based twist on the classic dish, packed with rich, creamy flavors and the perfect balance of savory and tangy notes. Tender soy strips are simmered in a luxurious sauce.",
	// 		image:
	// 			"https://images.unsplash.com/photo-1547592180-85f173990554?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
	// 		prepTime: 25,
	// 		rating: 4.5,
	// 		reviewCount: 143,
	// 		reviews: generateSampleReviews(12, 4.5),
	// 		servingSize: 4,
	// 		vegan: true,
	// 		vegetarian: true,
	// 		mealTime: ["dinner"],
	// 		cuisineType: ["italian", "fusion"],
	// 		dishType: ["main", "pasta"],
	// 		allergens: ["soy"],
	// 		nutritionalInfo: {
	// 			calories: 510,
	// 			fiber: 6,
	// 			protein: 22,
	// 			carbs: 45,
	// 			fat: 18,
	// 		},
	// 		ingredients: [
	// 			{ name: "dried soy strips", quantity: "1", unit: "cup" },
	// 			{ name: "olive oil", quantity: "1", unit: "tbsp" },
	// 			{ name: "salt", quantity: "1/2", unit: "tsp" },
	// 			{ name: "garlic", quantity: "3", unit: "cloves" },
	// 			{ name: "nutritional yeast", quantity: "2", unit: "tbsp" },
	// 			{ name: "coconut milk", quantity: "1", unit: "cup" },
	// 			{ name: "sun-dried tomatoes", quantity: "1/3", unit: "cup" },
	// 			{ name: "fresh basil", quantity: "1/4", unit: "cup" },
	// 		],
	// 		instructions: [
	// 			"Rehydrate soy strips according to package instructions, then drain well.",
	// 			"Heat olive oil in a large skillet over medium heat.",
	// 			"Add minced garlic and cook until fragrant, about 1 minute.",
	// 			"Add soy strips and cook until slightly browned, about 5 minutes.",
	// 			"Add sun-dried tomatoes, coconut milk, and nutritional yeast. Stir well.",
	// 			"Simmer for 10-15 minutes until sauce thickens.",
	// 			"Season with salt to taste and garnish with fresh basil before serving.",
	// 		],
	// 		tags: ["vegan", "dinner", "high-protein", "plant-based"],
	// 	},
	// 	{
	// 		id: "2",
	// 		name: "Creamy Mushroom Risotto",
	// 		description:
	// 			"A rich and creamy Italian risotto made with arborio rice and fresh mushrooms. This comforting dish is perfect for a cozy dinner.",
	// 		image:
	// 			"https://images.unsplash.com/photo-1476124369491-e7addf5db371?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
	// 		prepTime: 35,
	// 		rating: 4.7,
	// 		reviewCount: 89,
	// 		reviews: generateSampleReviews(8, 4.7),
	// 		servingSize: 2,
	// 		vegan: false,
	// 		vegetarian: true,
	// 		mealTime: ["dinner"],
	// 		cuisineType: ["italian"],
	// 		dishType: ["main", "rice"],
	// 		allergens: ["dairy"],
	// 		nutritionalInfo: {
	// 			calories: 450,
	// 			fiber: 3,
	// 			protein: 10,
	// 			carbs: 65,
	// 			fat: 12,
	// 		},
	// 		ingredients: [
	// 			{ name: "arborio rice", quantity: "1", unit: "cup" },
	// 			{ name: "mushrooms", quantity: "8", unit: "oz" },
	// 			{ name: "vegetable broth", quantity: "4", unit: "cups" },
	// 			{ name: "white wine", quantity: "1/2", unit: "cup" },
	// 			{ name: "onion", quantity: "1", unit: "medium" },
	// 			{ name: "garlic", quantity: "2", unit: "cloves" },
	// 			{ name: "parmesan cheese", quantity: "1/2", unit: "cup" },
	// 			{ name: "butter", quantity: "2", unit: "tbsp" },
	// 			{ name: "olive oil", quantity: "1", unit: "tbsp" },
	// 			{ name: "fresh thyme", quantity: "1", unit: "tsp" },
	// 		],
	// 		instructions: [
	// 			"Heat broth in a saucepan and keep warm.",
	// 			"In a large pan, heat olive oil and 1 tbsp butter. Add diced onion and cook until translucent.",
	// 			"Add sliced mushrooms and minced garlic, cook until mushrooms are soft.",
	// 			"Add arborio rice and stir for 1-2 minutes until translucent at the edges.",
	// 			"Add white wine and stir until absorbed.",
	// 			"Add warm broth one ladle at a time, stirring constantly until each addition is absorbed.",
	// 			"Continue adding broth until rice is creamy and al dente, about 20-25 minutes.",
	// 			"Remove from heat, stir in remaining butter and parmesan cheese.",
	// 			"Season with salt, pepper, and fresh thyme. Let stand for 2 minutes before serving.",
	// 		],
	// 		tags: ["vegetarian", "dinner", "italian", "comfort-food"],
	// 	},
	// 	{
	// 		id: "3",
	// 		name: "Spicy Black Bean Tacos",
	// 		description:
	// 			"Quick and flavorful vegan tacos filled with spicy black beans, fresh vegetables, and zesty lime. A perfect weeknight dinner option that's ready in minutes.",
	// 		image:
	// 			"https://images.unsplash.com/photo-1565299585323-38d6b0865b47?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1080&q=80",
	// 		prepTime: 20,
	// 		rating: 4.3,
	// 		reviewCount: 112,
	// 		reviews: generateSampleReviews(10, 4.3),
	// 		servingSize: 4,
	// 		vegan: true,
	// 		vegetarian: true,
	// 		mealTime: ["lunch", "dinner"],
	// 		cuisineType: ["mexican", "tex-mex"],
	// 		dishType: ["main", "tacos"],
	// 		allergens: [],
	// 		nutritionalInfo: {
	// 			calories: 320,
	// 			fiber: 12,
	// 			protein: 15,
	// 			carbs: 48,
	// 			fat: 8,
	// 		},
	// 		ingredients: [
	// 			{ name: "corn tortillas", quantity: "8", unit: "" },
	// 			{ name: "black beans", quantity: "1", unit: "can" },
	// 			{ name: "red onion", quantity: "1/2", unit: "" },
	// 			{ name: "bell pepper", quantity: "1", unit: "" },
	// 			{ name: "avocado", quantity: "1", unit: "" },
	// 			{ name: "lime", quantity: "1", unit: "" },
	// 			{ name: "cilantro", quantity: "1/4", unit: "cup" },
	// 			{ name: "cumin", quantity: "1", unit: "tsp" },
	// 			{ name: "chili powder", quantity: "1", unit: "tsp" },
	// 			{ name: "garlic powder", quantity: "1/2", unit: "tsp" },
	// 		],
	// 		instructions: [
	// 			"Drain and rinse black beans. In a saucepan, combine beans with cumin, chili powder, and garlic powder.",
	// 			"Heat beans over medium heat for 5 minutes, mashing slightly.",
	// 			"Dice bell pepper and red onion. Slice avocado and chop cilantro.",
	// 			"Warm tortillas in a dry skillet or microwave.",
	// 			"Assemble tacos with beans, vegetables, avocado, and cilantro.",
	// 			"Squeeze fresh lime juice over tacos before serving.",
	// 		],
	// 		tags: ["vegan", "mexican", "quick", "dinner", "lunch"],
	// 	},
	// 	{
	// 		id: "4",
	// 		name: "Blueberry Oatmeal Breakfast Bowl",
	// 		description:
	// 			"A hearty and nutritious breakfast bowl with creamy oatmeal, fresh blueberries, and crunchy nuts. Perfect for starting your day with energy.",
	// 		image:
	// 			"https://images.unsplash.com/photo-1490474504059-bf2db5ab2348?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1080&q=80",
	// 		prepTime: 10,
	// 		rating: 4.8,
	// 		reviewCount: 76,
	// 		reviews: generateSampleReviews(7, 4.8),
	// 		servingSize: 1,
	// 		vegan: true,
	// 		vegetarian: true,
	// 		mealTime: ["breakfast"],
	// 		cuisineType: ["american", "international"],
	// 		dishType: ["breakfast", "porridge"],
	// 		allergens: ["nuts"],
	// 		nutritionalInfo: {
	// 			calories: 280,
	// 			fiber: 8,
	// 			protein: 10,
	// 			carbs: 42,
	// 			fat: 9,
	// 		},
	// 		ingredients: [
	// 			{ name: "rolled oats", quantity: "1/2", unit: "cup" },
	// 			{ name: "almond milk", quantity: "1", unit: "cup" },
	// 			{ name: "blueberries", quantity: "1/2", unit: "cup" },
	// 			{ name: "banana", quantity: "1/2", unit: "" },
	// 			{ name: "maple syrup", quantity: "1", unit: "tbsp" },
	// 			{ name: "cinnamon", quantity: "1/4", unit: "tsp" },
	// 			{ name: "walnuts", quantity: "2", unit: "tbsp" },
	// 			{ name: "chia seeds", quantity: "1", unit: "tsp" },
	// 		],
	// 		instructions: [
	// 			"Combine oats and almond milk in a small saucepan over medium heat.",
	// 			"Bring to a simmer and cook for 5 minutes, stirring occasionally.",
	// 			"Remove from heat and stir in cinnamon and maple syrup.",
	// 			"Transfer to a bowl and top with sliced banana, blueberries, walnuts, and chia seeds.",
	// 			"Serve immediately while warm.",
	// 		],
	// 		tags: ["breakfast", "vegan", "quick", "healthy", "gluten-free"],
	// 	},
	// 	{
	// 		id: "5",
	// 		name: "Thai Green Curry with Tofu",
	// 		description:
	// 			"A fragrant and spicy Thai green curry with crispy tofu and colorful vegetables. This aromatic dish is full of authentic flavors and can be adjusted to your preferred spice level.",
	// 		image:
	// 			"https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1080&q=80",
	// 		prepTime: 30,
	// 		rating: 4.6,
	// 		reviewCount: 104,
	// 		reviews: generateSampleReviews(9, 4.6),
	// 		servingSize: 3,
	// 		vegan: true,
	// 		vegetarian: true,
	// 		mealTime: ["dinner"],
	// 		cuisineType: ["thai", "asian"],
	// 		dishType: ["main", "curry"],
	// 		allergens: ["soy"],
	// 		nutritionalInfo: {
	// 			calories: 380,
	// 			fiber: 5,
	// 			protein: 18,
	// 			carbs: 30,
	// 			fat: 22,
	// 		},
	// 		ingredients: [
	// 			{ name: "firm tofu", quantity: "14", unit: "oz" },
	// 			{ name: "green curry paste", quantity: "2", unit: "tbsp" },
	// 			{ name: "coconut milk", quantity: "1", unit: "can" },
	// 			{ name: "broccoli", quantity: "1", unit: "head" },
	// 			{ name: "bell pepper", quantity: "1", unit: "" },
	// 			{ name: "carrots", quantity: "2", unit: "" },
	// 			{ name: "lime leaves", quantity: "3", unit: "" },
	// 			{ name: "lemongrass", quantity: "1", unit: "stalk" },
	// 			{ name: "ginger", quantity: "1", unit: "inch" },
	// 			{ name: "garlic", quantity: "2", unit: "cloves" },
	// 			{ name: "soy sauce", quantity: "1", unit: "tbsp" },
	// 			{ name: "brown sugar", quantity: "1", unit: "tsp" },
	// 			{ name: "lime", quantity: "1", unit: "" },
	// 			{ name: "fresh basil", quantity: "1/4", unit: "cup" },
	// 		],
	// 		instructions: [
	// 			"Press tofu to remove excess water, then cut into cubes.",
	// 			"Heat oil in a pan and fry tofu until golden and crispy. Set aside.",
	// 			"In a large pot, heat a little oil and add minced garlic, ginger, and lemongrass. Cook for 1 minute.",
	// 			"Add green curry paste and cook for another minute until fragrant.",
	// 			"Pour in coconut milk, add lime leaves, soy sauce, and brown sugar. Bring to a simmer.",
	// 			"Add chopped vegetables and cook for 5-7 minutes until tender but still crisp.",
	// 			"Add the crispy tofu and simmer for another 2 minutes.",
	// 			"Remove from heat, stir in fresh lime juice and basil leaves.",
	// 			"Serve hot with rice or noodles.",
	// 		],
	// 		tags: ["vegan", "thai", "spicy", "dinner", "asian"],
	// 	},
	// 	{
	// 		id: "6",
	// 		name: "Chocolate Avocado Mousse",
	// 		description:
	// 			"A decadent yet healthy dessert made with ripe avocados and rich chocolate. This creamy mousse is surprisingly nutritious and takes just minutes to prepare.",
	// 		image:
	// 			"https://images.unsplash.com/photo-1511381939415-e44015466834?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1080&q=80",
	// 		prepTime: 15,
	// 		rating: 4.4,
	// 		reviewCount: 68,
	// 		reviews: generateSampleReviews(6, 4.4),
	// 		servingSize: 2,
	// 		vegan: true,
	// 		vegetarian: true,
	// 		mealTime: ["dessert", "snack"],
	// 		cuisineType: ["international", "fusion"],
	// 		dishType: ["dessert", "mousse"],
	// 		allergens: [],
	// 		nutritionalInfo: {
	// 			calories: 220,
	// 			fiber: 7,
	// 			protein: 4,
	// 			carbs: 22,
	// 			fat: 16,
	// 		},
	// 		ingredients: [
	// 			{ name: "ripe avocados", quantity: "2", unit: "" },
	// 			{ name: "cocoa powder", quantity: "1/3", unit: "cup" },
	// 			{ name: "maple syrup", quantity: "1/4", unit: "cup" },
	// 			{ name: "vanilla extract", quantity: "1", unit: "tsp" },
	// 			{ name: "almond milk", quantity: "2", unit: "tbsp" },
	// 			{ name: "salt", quantity: "1/8", unit: "tsp" },
	// 			{ name: "dark chocolate chips", quantity: "2", unit: "tbsp" },
	// 			{ name: "fresh berries", quantity: "1/2", unit: "cup" },
	// 		],
	// 		instructions: [
	// 			"Cut avocados in half, remove pits, and scoop flesh into a food processor.",
	// 			"Add cocoa powder, maple syrup, vanilla extract, almond milk, and salt.",
	// 			"Process until completely smooth, stopping to scrape down the sides as needed.",
	// 			"Taste and adjust sweetness if necessary.",
	// 			"Spoon into serving glasses and refrigerate for at least 30 minutes.",
	// 			"Before serving, top with dark chocolate chips and fresh berries.",
	// 		],
	// 		tags: ["dessert", "vegan", "gluten-free", "no-bake", "quick"],
	// 	},
	// ];
	[
		{
			id: "0",
			name: "Creamy Mushroom Risotto",
			description:
				"Indulge in the luxurious Creamy Mushroom Risotto, where each bite offers a symphony of rich, earthy mushrooms and velvety rice, perfect for a comforting dinner that feels like a warm embrace.",
			image: "0.webp",
			prepTime: 40,
			rating: 4.7,
			reviewCount: 100,
			reviews: [],
			servingSize: 2,
			vegan: false,
			vegetarian: true,
			mealTime: ["dinner"],
			cuisineType: ["Italian"],
			dishType: ["risotto", "main course"],
			allergens: ["Milk", "Mushroom"],
			nutritionalInfo: {
				calories: 550,
				fiber: 6,
				protein: 12,
				carbs: 70,
				fat: 20,
			},
			ingredients: [
				{ name: "arborio rice", quantity: "1", unit: "cup" },
				{ name: "mushrooms", quantity: "200", unit: "g" },
				{ name: "milk", quantity: "1", unit: "cup" },
				{ name: "onion", quantity: "1", unit: "small" },
				{ name: "garlic", quantity: "2", unit: "cloves" },
				{ name: "vegetable broth", quantity: "3", unit: "cups" },
				{ name: "parmesan cheese", quantity: "1/2", unit: "cup" },
				{ name: "olive oil", quantity: "1", unit: "tbsp" },
				{ name: "salt", quantity: "1/2", unit: "tsp" },
				{ name: "black pepper", quantity: "1/4", unit: "tsp" },
			],
			instructions: [
				"Warm the vegetable broth in a separate saucepan and keep it at a gentle simmer.",
				"In a large skillet or saucepan, heat the olive oil over medium heat. Sauté the finely chopped onion until translucent, about 3-4 minutes.",
				"Add minced garlic and mushrooms. Cook until mushrooms start to brown and release moisture.",
				"Stir in the arborio rice, allowing it to toast lightly for about 1 minute without browning the garlic.",
				"Begin adding the warm broth one ladle at a time, stirring constantly. Let each ladleful absorb before adding the next.",
				"Once the rice is almost al dente (about 18-20 minutes), stir in the milk and parmesan cheese. Season with salt and pepper to taste.",
				"Continue to cook for another 2-3 minutes, stirring gently, until the risotto is creamy and the rice is fully cooked. Serve hot.",
			],
			tags: ["creamy", "risotto", "mushroom"],
		},
		{
			id: "1",
			name: "Sesame Tofu Stir-fry",
			description:
				"Experience a burst of vibrant flavors with our Sesame Tofu Stir-fry, where crispy tofu meets a medley of colorful vegetables, all tossed in a bold, savory sauce that dances on your palate.",
			image: "1.webp",
			prepTime: 25,
			rating: 4.5,
			reviewCount: 80,
			reviews: [],
			servingSize: 3,
			vegan: true,
			vegetarian: true,
			mealTime: ["dinner"],
			cuisineType: ["Asian"],
			dishType: ["stir-fry", "main"],
			allergens: ["Soy", "Sesame"],
			nutritionalInfo: {
				calories: 450,
				fiber: 5,
				protein: 18,
				carbs: 30,
				fat: 22,
			},
			ingredients: [
				{ name: "tofu (firm)", quantity: "200", unit: "g" },
				{ name: "sesame oil", quantity: "2", unit: "tbsp" },
				{ name: "soy sauce", quantity: "2", unit: "tbsp" },
				{ name: "garlic", quantity: "2", unit: "cloves" },
				{ name: "ginger (fresh)", quantity: "1", unit: "tsp" },
				{ name: "broccoli florets", quantity: "1", unit: "cup" },
				{ name: "bell pepper", quantity: "1", unit: "medium" },
				{ name: "sesame seeds", quantity: "1", unit: "tbsp" },
				{ name: "cornstarch", quantity: "1", unit: "tsp" },
				{ name: "water", quantity: "1/4", unit: "cup" },
			],
			instructions: [
				"Drain and press the tofu to remove excess water, then cut into bite-sized cubes.",
				"In a small bowl, whisk together soy sauce, cornstarch, and water to make a slurry. Set aside.",
				"Heat sesame oil in a wok or large skillet over high heat. Add tofu cubes and stir-fry until golden on all sides, about 5-6 minutes.",
				"Add minced garlic and grated ginger, cooking for another 30 seconds to release their aromatics.",
				"Toss in chopped bell pepper and broccoli florets, stir-frying until vegetables are crisp-tender, about 3-4 minutes.",
				"Pour in the soy sauce slurry, stirring quickly to coat tofu and vegetables. The sauce will thicken as it cooks.",
				"Sprinkle sesame seeds on top and serve hot with steamed rice or noodles.",
			],
			tags: ["sesame", "tofu", "stir-fry"],
		},
		{
			id: "2",
			name: "Nutty Apple Quinoa Bowl",
			description:
				"Savor the wholesome goodness of our Nutty Apple Quinoa Bowl, a delightful fusion of crunchy nuts and sweet apples, nestled in a bed of fluffy quinoa for a refreshing and healthy lunch.",
			image: "2.webp",
			prepTime: 20,
			rating: 4.6,
			reviewCount: 60,
			reviews: [],
			servingSize: 1,
			vegan: true,
			vegetarian: true,
			mealTime: ["lunch"],
			cuisineType: ["Fusion"],
			dishType: ["bowl", "salad"],
			allergens: ["Nuts", "Apple"],
			nutritionalInfo: {
				calories: 400,
				fiber: 8,
				protein: 10,
				carbs: 55,
				fat: 15,
			},
			ingredients: [
				{ name: "quinoa (dry)", quantity: "1", unit: "cup" },
				{ name: "apple", quantity: "1", unit: "medium" },
				{ name: "mixed nuts", quantity: "1/4", unit: "cup" },
				{ name: "onion (red)", quantity: "2", unit: "tbsp" },
				{ name: "olive oil", quantity: "1", unit: "tbsp" },
				{ name: "apple cider vinegar", quantity: "1", unit: "tbsp" },
				{ name: "salt", quantity: "1/2", unit: "tsp" },
				{ name: "black pepper", quantity: "1/4", unit: "tsp" },
			],
			instructions: [
				"Rinse quinoa under cold water. In a saucepan, combine quinoa with 2 cups of water. Bring to a boil, then reduce heat and simmer for 15 minutes or until the liquid is absorbed.",
				"Dice the apple into small cubes and finely chop the red onion.",
				"In a small bowl, whisk together olive oil, apple cider vinegar, salt, and pepper to form a dressing.",
				"Fluff the cooked quinoa with a fork and transfer it to a large bowl.",
				"Add the diced apple, red onion, and mixed nuts to the quinoa. Pour the dressing over the top.",
				"Toss gently to combine all ingredients. Adjust seasoning if needed.",
				"Serve warm or cold as a light and refreshing meal.",
			],
			tags: ["nutty", "quinoa", "healthy"],
		},
		{
			id: "3",
			name: "Carrot Ginger Soup",
			description:
				"Warm your soul with our Carrot Ginger Soup, a harmonious blend of sweet carrots and zesty ginger, simmered to perfection for a soothing and spicy delight.",
			image: "3.webp",
			prepTime: 30,
			rating: 4.4,
			reviewCount: 70,
			reviews: [],
			servingSize: 4,
			vegan: true,
			vegetarian: true,
			mealTime: ["dinner"],
			cuisineType: ["Asian"],
			dishType: ["soup"],
			allergens: ["Carrot"],
			nutritionalInfo: {
				calories: 300,
				fiber: 7,
				protein: 5,
				carbs: 40,
				fat: 8,
			},
			ingredients: [
				{ name: "carrots", quantity: "4", unit: "large" },
				{ name: "ginger (fresh)", quantity: "1", unit: "tbsp" },
				{ name: "onion", quantity: "1", unit: "small" },
				{ name: "vegetable broth", quantity: "4", unit: "cups" },
				{ name: "olive oil", quantity: "1", unit: "tbsp" },
				{ name: "salt", quantity: "1", unit: "tsp" },
				{ name: "black pepper", quantity: "1/2", unit: "tsp" },
			],
			instructions: [
				"Peel and slice the carrots. Dice the onion and finely chop the fresh ginger.",
				"Warm olive oil in a large pot over medium heat. Sauté the onion until translucent, about 3-4 minutes.",
				"Add sliced carrots and ginger. Stir for another 2 minutes to release flavors.",
				"Pour in the vegetable broth and bring to a boil.",
				"Reduce the heat to low, cover, and simmer for about 15-20 minutes or until the carrots are very tender.",
				"Use an immersion blender (or a stand blender in batches) to puree the soup until smooth.",
				"Season with salt and black pepper. Serve hot with a drizzle of olive oil or a dollop of coconut cream if desired.",
			],
			tags: ["soup", "carrot", "ginger"],
		},
		{
			id: "4",
			name: "Cheesy Broccoli Casserole",
			description:
				"Dive into the comforting embrace of our Cheesy Broccoli Casserole, where tender broccoli florets are enveloped in a creamy, cheesy sauce, baked to golden perfection.",
			image: "4.webp",
			prepTime: 45,
			rating: 4.3,
			reviewCount: 90,
			reviews: [],
			servingSize: 4,
			vegan: false,
			vegetarian: true,
			mealTime: ["dinner"],
			cuisineType: ["American"],
			dishType: ["casserole"],
			allergens: ["Milk", "Wheat"],
			nutritionalInfo: {
				calories: 600,
				fiber: 8,
				protein: 20,
				carbs: 50,
				fat: 25,
			},
			ingredients: [
				{ name: "broccoli florets", quantity: "2", unit: "cups" },
				{ name: "cheddar cheese", quantity: "1", unit: "cup" },
				{ name: "cream of mushroom soup", quantity: "1", unit: "can" },
				{ name: "milk", quantity: "1/2", unit: "cup" },
				{ name: "breadcrumbs", quantity: "1/2", unit: "cup" },
				{ name: "onion powder", quantity: "1/2", unit: "tsp" },
				{ name: "salt", quantity: "1", unit: "tsp" },
				{ name: "black pepper", quantity: "1/2", unit: "tsp" },
			],
			instructions: [
				"Preheat your oven to 375°F (190°C). Lightly grease a baking dish.",
				"Blanch broccoli florets in boiling water for 2-3 minutes, then drain and set aside.",
				"In a mixing bowl, whisk together the cream of mushroom soup, milk, onion powder, salt, and black pepper.",
				"Stir half of the cheddar cheese into the soup mixture.",
				"Arrange the blanched broccoli florets in the baking dish and pour the soup-cheese mixture over the top.",
				"Sprinkle the remaining cheddar cheese and breadcrumbs evenly over the casserole.",
				"Bake for 20-25 minutes or until the top is golden and bubbly. Let it cool slightly before serving.",
			],
			tags: ["cheesy", "casserole", "broccoli"],
		},
		{
			id: "5",
			name: "Spiced Lentil Stew",
			description:
				"Embark on a culinary journey with our Spiced Lentil Stew, a hearty blend of lentils and aromatic spices that create a symphony of flavors, perfect for a cozy evening.",
			image: "5.webp",
			prepTime: 40,
			rating: 4.5,
			reviewCount: 85,
			reviews: [],
			servingSize: 4,
			vegan: true,
			vegetarian: true,
			mealTime: ["dinner"],
			cuisineType: ["Middle Eastern"],
			dishType: ["stew"],
			allergens: [],
			nutritionalInfo: {
				calories: 350,
				fiber: 12,
				protein: 18,
				carbs: 45,
				fat: 8,
			},
			ingredients: [
				{ name: "lentils (dry)", quantity: "1", unit: "cup" },
				{ name: "tomato paste", quantity: "2", unit: "tbsp" },
				{ name: "onion", quantity: "1", unit: "medium" },
				{ name: "garlic", quantity: "2", unit: "cloves" },
				{ name: "cumin", quantity: "1", unit: "tsp" },
				{ name: "paprika", quantity: "1", unit: "tsp" },
				{ name: "vegetable broth", quantity: "4", unit: "cups" },
				{ name: "olive oil", quantity: "1", unit: "tbsp" },
				{ name: "salt", quantity: "1", unit: "tsp" },
				{ name: "black pepper", quantity: "1/2", unit: "tsp" },
			],
			instructions: [
				"Rinse lentils and set aside. Dice the onion and mince the garlic.",
				"In a large pot, heat the olive oil over medium heat. Sauté onion until lightly browned, about 5 minutes.",
				"Add garlic, cumin, and paprika. Stir for 30 seconds to let the spices bloom.",
				"Add tomato paste and lentils, mixing well to coat with the spices.",
				"Pour in the vegetable broth, bring the stew to a boil, then reduce heat to low.",
				"Simmer for 20-25 minutes, or until lentils are tender and the stew has thickened.",
				"Season with salt and pepper. Serve hot with crusty bread or rice.",
			],
			tags: ["stew", "lentils", "spiced"],
		},
		{
			id: "6",
			name: "Eggplant Parmesan",
			description:
				"Relish the classic Italian flavors of our Eggplant Parmesan, where layers of tender eggplant, rich tomato sauce, and gooey cheese come together in a delightful harmony.",
			image: "6.webp",
			prepTime: 50,
			rating: 4.6,
			reviewCount: 110,
			reviews: [],
			servingSize: 3,
			vegan: false,
			vegetarian: true,
			mealTime: ["dinner"],
			cuisineType: ["Italian"],
			dishType: ["main", "casserole"],
			allergens: ["Milk", "Wheat", "Eggs"],
			nutritionalInfo: {
				calories: 500,
				fiber: 7,
				protein: 22,
				carbs: 55,
				fat: 18,
			},
			ingredients: [
				{ name: "eggplant", quantity: "2", unit: "large" },
				{ name: "breadcrumbs", quantity: "1", unit: "cup" },
				{ name: "eggs", quantity: "2", unit: "" },
				{ name: "mozzarella cheese", quantity: "1", unit: "cup" },
				{ name: "tomato sauce", quantity: "1", unit: "cup" },
				{ name: "parmesan cheese", quantity: "1/2", unit: "cup" },
				{ name: "olive oil", quantity: "2", unit: "tbsp" },
				{ name: "salt", quantity: "1", unit: "tsp" },
				{ name: "black pepper", quantity: "1/2", unit: "tsp" },
			],
			instructions: [
				"Preheat oven to 400°F (200°C). Slice eggplants into 1/2-inch rounds, and lightly sprinkle with salt to remove excess moisture. Pat dry after 10 minutes.",
				"Beat the eggs in a shallow bowl. Place breadcrumbs in another bowl.",
				"Dip each eggplant slice into the beaten eggs, then coat thoroughly with breadcrumbs.",
				"Heat olive oil in a skillet over medium-high heat. Fry eggplant slices until golden brown on both sides. Drain on paper towels.",
				"In a baking dish, spread a thin layer of tomato sauce. Arrange fried eggplant slices on top, followed by mozzarella cheese.",
				"Repeat layers as needed. Top with parmesan cheese, salt, and pepper.",
				"Bake for 15-20 minutes or until the cheese is bubbly and lightly browned. Serve hot.",
			],
			tags: ["eggplant", "parmesan", "italian"],
		},
		{
			id: "7",
			name: "Miso Glazed Eggplant",
			description:
				"Delight in the umami-rich Miso Glazed Eggplant, a perfect balance of sweet and savory that transforms a humble vegetable into a gourmet experience.",
			image: "7.webp",
			prepTime: 35,
			rating: 4.5,
			reviewCount: 75,
			reviews: [],
			servingSize: 2,
			vegan: true,
			vegetarian: true,
			mealTime: ["dinner"],
			cuisineType: ["Japanese"],
			dishType: ["glazed", "side"],
			allergens: ["Soy"],
			nutritionalInfo: {
				calories: 320,
				fiber: 5,
				protein: 8,
				carbs: 40,
				fat: 10,
			},
			ingredients: [
				{ name: "eggplant", quantity: "1", unit: "medium" },
				{ name: "miso paste (white)", quantity: "2", unit: "tbsp" },
				{ name: "mirin", quantity: "1", unit: "tbsp" },
				{ name: "soy sauce", quantity: "1", unit: "tbsp" },
				{ name: "sugar", quantity: "1", unit: "tsp" },
				{ name: "sesame oil", quantity: "1", unit: "tsp" },
				{ name: "green onion", quantity: "1", unit: "tbsp" },
			],
			instructions: [
				"Preheat oven to 375°F (190°C). Slice the eggplant in half lengthwise and score the flesh diagonally.",
				"In a small bowl, whisk together miso paste, mirin, soy sauce, sugar, and sesame oil until smooth.",
				"Brush the miso glaze onto the cut surface of the eggplant, making sure it seeps into the scored areas.",
				"Place the eggplant halves cut-side up on a baking sheet lined with parchment paper.",
				"Roast for about 25 minutes, or until the eggplant is tender and the glaze is caramelized.",
				"Garnish with chopped green onion before serving. Enjoy the sweet and savory flavors.",
			],
			tags: ["miso", "eggplant", "glazed"],
		},
		{
			id: "8",
			name: "Stuffed Bell Peppers",
			description:
				"Enjoy the vibrant colors and flavors of our Stuffed Bell Peppers, filled with a savory mix of grains and veggies, offering a wholesome and satisfying meal.",
			image: "8.webp",
			prepTime: 45,
			rating: 4.4,
			reviewCount: 95,
			reviews: [],
			servingSize: 4,
			vegan: true,
			vegetarian: true,
			mealTime: ["dinner"],
			cuisineType: ["Mediterranean"],
			dishType: ["main", "stuffed"],
			allergens: [],
			nutritionalInfo: {
				calories: 400,
				fiber: 6,
				protein: 15,
				carbs: 50,
				fat: 12,
			},
			ingredients: [
				{ name: "bell peppers", quantity: "4", unit: "large" },
				{ name: "quinoa (cooked)", quantity: "1", unit: "cup" },
				{ name: "onion", quantity: "1/2", unit: "cup" },
				{ name: "tomatoes (diced)", quantity: "1/2", unit: "cup" },
				{ name: "garlic", quantity: "2", unit: "cloves" },
				{ name: "olive oil", quantity: "1", unit: "tbsp" },
				{ name: "oregano (dried)", quantity: "1", unit: "tsp" },
				{ name: "salt", quantity: "1", unit: "tsp" },
				{ name: "black pepper", quantity: "1/2", unit: "tsp" },
			],
			instructions: [
				"Preheat oven to 375°F (190°C). Cut the tops off the bell peppers and remove seeds and membranes.",
				"Heat olive oil in a skillet over medium heat. Sauté diced onion and minced garlic until fragrant, about 3 minutes.",
				"Add diced tomatoes, quinoa, oregano, salt, and black pepper. Cook for another 2-3 minutes, stirring occasionally.",
				"Spoon the quinoa mixture into each bell pepper cavity.",
				"Place stuffed peppers upright in a baking dish with a little water or broth at the bottom to prevent sticking.",
				"Cover loosely with foil and bake for 25-30 minutes, or until peppers are tender.",
				"Remove foil and bake uncovered for an additional 5 minutes for a slight char on top.",
			],
			tags: ["stuffed", "bell peppers", "vegetarian"],
		},
		{
			id: "9",
			name: "Mushroom Stroganoff",
			description:
				"Indulge in the creamy decadence of our Mushroom Stroganoff, where tender mushrooms are bathed in a rich sauce, creating a comforting and flavorful dish.",
			image: "9.webp",
			prepTime: 35,
			rating: 4.6,
			reviewCount: 88,
			reviews: [],
			servingSize: 3,
			vegan: false,
			vegetarian: true,
			mealTime: ["dinner"],
			cuisineType: ["Russian"],
			dishType: ["stew", "pasta"],
			allergens: ["Milk", "Wheat", "Mushroom"],
			nutritionalInfo: {
				calories: 480,
				fiber: 5,
				protein: 12,
				carbs: 60,
				fat: 18,
			},
			ingredients: [
				{ name: "mixed mushrooms", quantity: "300", unit: "g" },
				{ name: "sour cream", quantity: "1/2", unit: "cup" },
				{ name: "onion", quantity: "1", unit: "small" },
				{ name: "garlic", quantity: "2", unit: "cloves" },
				{ name: "butter", quantity: "2", unit: "tbsp" },
				{ name: "flour (all-purpose)", quantity: "1", unit: "tbsp" },
				{ name: "vegetable broth", quantity: "1", unit: "cup" },
				{ name: "salt", quantity: "1/2", unit: "tsp" },
				{ name: "black pepper", quantity: "1/4", unit: "tsp" },
				{ name: "egg noodles (cooked)", quantity: "2", unit: "cups" },
			],
			instructions: [
				"Clean and slice the mushrooms. Finely chop the onion and mince the garlic.",
				"Melt butter in a large skillet over medium-high heat. Sauté onion for 3-4 minutes until soft.",
				"Add garlic and sliced mushrooms. Cook until mushrooms release their moisture and begin to brown, about 5 minutes.",
				"Sprinkle in the flour and stir for 1 minute to coat the mushrooms and onion.",
				"Gradually pour in the vegetable broth, stirring continuously to avoid lumps. Simmer for a few minutes until slightly thickened.",
				"Reduce heat to low and stir in sour cream. Season with salt and pepper.",
				"Serve the stroganoff over cooked egg noodles, garnished with fresh herbs if desired.",
			],
			tags: ["mushroom", "stroganoff", "creamy"],
		},
		{
			id: "10",
			name: "Apple Cinnamon Oatmeal",
			description:
				"Start your day with the warm embrace of our Apple Cinnamon Oatmeal, a comforting blend of sweet apples and aromatic cinnamon, perfect for a cozy breakfast.",
			image: "10.webp",
			prepTime: 15,
			rating: 4.7,
			reviewCount: 65,
			reviews: [],
			servingSize: 1,
			vegan: true,
			vegetarian: true,
			mealTime: ["breakfast"],
			cuisineType: ["American"],
			dishType: ["oatmeal", "breakfast"],
			allergens: ["Apple"],
			nutritionalInfo: {
				calories: 350,
				fiber: 6,
				protein: 8,
				carbs: 55,
				fat: 5,
			},
			ingredients: [
				{ name: "rolled oats", quantity: "1/2", unit: "cup" },
				{ name: "apple", quantity: "1", unit: "medium" },
				{ name: "cinnamon", quantity: "1/2", unit: "tsp" },
				{ name: "water or milk", quantity: "1", unit: "cup" },
				{ name: "salt", quantity: "1/8", unit: "tsp" },
				{ name: "brown sugar (optional)", quantity: "1", unit: "tbsp" },
				{ name: "chopped walnuts (optional)", quantity: "1", unit: "tbsp" },
			],
			instructions: [
				"Peel and dice the apple into small chunks (you can leave the skin on if you prefer).",
				"In a small saucepan, bring the water or milk to a gentle boil with a pinch of salt.",
				"Stir in the rolled oats, diced apple, and cinnamon. Reduce the heat to low.",
				"Cook for 5-7 minutes, stirring occasionally, until the oats are creamy and the apple is slightly softened.",
				"Taste and add brown sugar if desired for sweetness.",
				"Serve hot, topping with chopped walnuts for added crunch and extra flavor.",
			],
			tags: ["oatmeal", "apple", "cinnamon"],
		},
		{
			id: "11",
			name: "Carrot Cake Muffins",
			description:
				"Treat yourself to our moist Carrot Cake Muffins, where the sweetness of carrots meets the warmth of spices, creating a delightful snack or breakfast.",
			image: "11.webp",
			prepTime: 30,
			rating: 4.5,
			reviewCount: 90,
			reviews: [],
			servingSize: 2,
			vegan: false,
			vegetarian: true,
			mealTime: ["breakfast"],
			cuisineType: ["American"],
			dishType: ["muffins", "baked goods"],
			allergens: ["Carrot", "Wheat", "Eggs", "Nuts", "Milk"],
			nutritionalInfo: {
				calories: 400,
				fiber: 4,
				protein: 8,
				carbs: 50,
				fat: 15,
			},
			ingredients: [
				{ name: "grated carrots", quantity: "1", unit: "cup" },
				{ name: "all-purpose flour", quantity: "1", unit: "cup" },
				{ name: "sugar", quantity: "1/2", unit: "cup" },
				{ name: "baking powder", quantity: "1", unit: "tsp" },
				{ name: "cinnamon", quantity: "1", unit: "tsp" },
				{ name: "eggs", quantity: "1", unit: "" },
				{ name: "milk", quantity: "1/4", unit: "cup" },
				{ name: "vegetable oil", quantity: "2", unit: "tbsp" },
				{ name: "chopped walnuts", quantity: "1/4", unit: "cup" },
				{ name: "salt", quantity: "1/4", unit: "tsp" },
			],
			instructions: [
				"Preheat oven to 350°F (175°C). Line a muffin tin with paper liners.",
				"In a large bowl, whisk together flour, sugar, baking powder, cinnamon, and salt.",
				"In a separate bowl, beat the egg with milk and vegetable oil.",
				"Stir the wet mixture into the dry ingredients until just combined (do not overmix).",
				"Fold in the grated carrots and chopped walnuts.",
				"Fill the muffin liners about 3/4 full and bake for 18-20 minutes, or until a toothpick comes out clean.",
				"Allow to cool on a wire rack before serving.",
			],
			tags: ["carrot", "muffins", "cake"],
		},
		{
			id: "12",
			name: "Vegan Pad Thai",
			description:
				"Savor the tangy and savory notes of our Vegan Pad Thai, a delightful noodle dish that brings the vibrant flavors of Thailand to your table.",
			image: "12.webp",
			prepTime: 30,
			rating: 4.6,
			reviewCount: 105,
			reviews: [],
			servingSize: 2,
			vegan: true,
			vegetarian: true,
			mealTime: ["dinner"],
			cuisineType: ["Thai"],
			dishType: ["noodles", "stir-fry"],
			allergens: ["Soy", "Nuts", "Wheat"],
			nutritionalInfo: {
				calories: 450,
				fiber: 4,
				protein: 15,
				carbs: 60,
				fat: 12,
			},
			ingredients: [
				{ name: "rice noodles", quantity: "200", unit: "g" },
				{ name: "tofu (firm)", quantity: "150", unit: "g" },
				{ name: "bean sprouts", quantity: "1", unit: "cup" },
				{ name: "peanuts (crushed)", quantity: "1/4", unit: "cup" },
				{ name: "pad thai sauce", quantity: "1/3", unit: "cup" },
				{ name: "green onion", quantity: "2", unit: "tbsp" },
				{ name: "lime", quantity: "1/2", unit: "" },
				{ name: "oil (for stir-frying)", quantity: "1", unit: "tbsp" },
			],
			instructions: [
				"Soak the rice noodles in warm water until softened, about 10-15 minutes. Drain well.",
				"Cut tofu into small cubes and pat dry.",
				"Heat oil in a wok over medium-high heat. Stir-fry tofu until lightly golden, about 3-4 minutes.",
				"Add the drained rice noodles and pad thai sauce, tossing to combine.",
				"Stir in bean sprouts and chopped green onions. Cook for another 1-2 minutes.",
				"Remove from heat and garnish with crushed peanuts and a squeeze of lime juice.",
				"Serve hot and enjoy the balance of tangy, sweet, and savory flavors.",
			],
			tags: ["pad thai", "vegan", "noodles"],
		},
		{
			id: "13",
			name: "Garlic Butter Mushroom Pasta",
			description:
				"Indulge in the rich flavors of our Garlic Butter Mushroom Pasta, where hearty mushrooms and a luscious garlic butter sauce create a symphony of taste.",
			image: "13.webp",
			prepTime: 25,
			rating: 4.5,
			reviewCount: 95,
			reviews: [],
			servingSize: 3,
			vegan: false,
			vegetarian: true,
			mealTime: ["dinner"],
			cuisineType: ["Italian"],
			dishType: ["pasta", "main"],
			allergens: ["Milk", "Wheat", "Mushroom"],
			nutritionalInfo: {
				calories: 500,
				fiber: 5,
				protein: 14,
				carbs: 65,
				fat: 22,
			},
			ingredients: [
				{ name: "pasta (fettuccine or spaghetti)", quantity: "200", unit: "g" },
				{ name: "mushrooms (sliced)", quantity: "150", unit: "g" },
				{ name: "butter", quantity: "2", unit: "tbsp" },
				{ name: "garlic", quantity: "3", unit: "cloves" },
				{ name: "parsley (fresh)", quantity: "2", unit: "tbsp" },
				{ name: "salt", quantity: "1/2", unit: "tsp" },
				{ name: "black pepper", quantity: "1/4", unit: "tsp" },
				{ name: "parmesan cheese (grated)", quantity: "1/4", unit: "cup" },
			],
			instructions: [
				"Cook the pasta in a large pot of salted boiling water until al dente. Reserve 1/2 cup of cooking water, then drain pasta.",
				"In a skillet, melt butter over medium-high heat. Sauté sliced mushrooms until golden brown.",
				"Add minced garlic and cook for about 1 minute, stirring frequently to prevent burning.",
				"Reduce heat to medium. Toss in the cooked pasta, a splash of reserved pasta water, salt, and black pepper.",
				"Stir in grated parmesan cheese until a glossy sauce forms (add more pasta water if needed).",
				"Sprinkle with chopped fresh parsley. Adjust seasoning to taste.",
				"Serve immediately with extra parmesan on top if desired.",
			],
			tags: ["garlic", "pasta", "mushroom"],
		},
		{
			id: "14",
			name: "Spicy Chickpea Curry",
			description:
				"Embark on a flavor adventure with our Spicy Chickpea Curry, bursting with bold Indian spices that create a hearty and satisfying dish.",
			image: "14.webp",
			prepTime: 35,
			rating: 4.7,
			reviewCount: 100,
			reviews: [],
			servingSize: 4,
			vegan: true,
			vegetarian: true,
			mealTime: ["dinner"],
			cuisineType: ["Indian"],
			dishType: ["curry", "stew"],
			allergens: [],
			nutritionalInfo: {
				calories: 420,
				fiber: 10,
				protein: 18,
				carbs: 55,
				fat: 14,
			},
			ingredients: [
				{ name: "chickpeas (canned)", quantity: "1", unit: "can" },
				{ name: "tomato sauce", quantity: "1", unit: "cup" },
				{ name: "onion", quantity: "1", unit: "small" },
				{ name: "garam masala", quantity: "1", unit: "tsp" },
				{ name: "turmeric", quantity: "1/2", unit: "tsp" },
				{ name: "chili powder", quantity: "1/2", unit: "tsp" },
				{ name: "ginger (fresh)", quantity: "1", unit: "tsp" },
				{ name: "salt", quantity: "1", unit: "tsp" },
				{ name: "oil", quantity: "1", unit: "tbsp" },
			],
			instructions: [
				"Dice the onion and grate the ginger. Drain and rinse the chickpeas.",
				"Heat oil in a pot over medium heat. Sauté onion until translucent, about 4 minutes.",
				"Add ginger, garam masala, turmeric, and chili powder. Stir for 30 seconds to release aromatics.",
				"Pour in the tomato sauce and simmer for 2-3 minutes.",
				"Add chickpeas and a splash of water or vegetable broth if needed. Season with salt.",
				"Cover and cook for 10-15 minutes until the flavors meld and the sauce thickens.",
				"Taste and adjust spices. Serve hot with rice or naan bread.",
			],
			tags: ["chickpea", "curry", "spicy"],
		},
		{
			id: "15",
			name: "Zucchini Fritters",
			description:
				"Enjoy the crispy delight of our Zucchini Fritters, where grated zucchini is transformed into golden patties, perfect as a snack or appetizer.",
			image: "15.webp",
			prepTime: 20,
			rating: 4.3,
			reviewCount: 70,
			reviews: [],
			servingSize: 2,
			vegan: false,
			vegetarian: true,
			mealTime: ["snack"],
			cuisineType: ["American"],
			dishType: ["fritters", "appetizer"],
			allergens: ["Eggs", "Wheat"],
			nutritionalInfo: {
				calories: 350,
				fiber: 4,
				protein: 8,
				carbs: 40,
				fat: 12,
			},
			ingredients: [
				{ name: "zucchini (grated)", quantity: "2", unit: "cups" },
				{ name: "all-purpose flour", quantity: "1/2", unit: "cup" },
				{ name: "egg", quantity: "1", unit: "" },
				{ name: "green onion", quantity: "2", unit: "tbsp" },
				{ name: "salt", quantity: "1/2", unit: "tsp" },
				{ name: "black pepper", quantity: "1/4", unit: "tsp" },
				{ name: "vegetable oil", quantity: "2", unit: "tbsp" },
			],
			instructions: [
				"Place grated zucchini in a colander and sprinkle with a pinch of salt. Let it sit for 10 minutes, then squeeze out excess moisture.",
				"In a bowl, combine the zucchini, flour, egg, chopped green onion, salt, and black pepper. Mix well to form a batter.",
				"Heat the vegetable oil in a nonstick skillet over medium-high heat.",
				"Scoop 2-3 tablespoons of batter per fritter into the skillet, flattening slightly.",
				"Cook for 2-3 minutes on each side, or until golden brown and crispy.",
				"Transfer to a paper towel-lined plate to drain excess oil.",
				"Serve hot with sour cream or a yogurt-based dipping sauce.",
			],
			tags: ["zucchini", "fritters", "crispy"],
		},
		{
			id: "16",
			name: "Sesame Noodles with Tofu",
			description:
				"Delight in the savory goodness of our Sesame Noodles with Tofu, where tender noodles and crispy tofu are tossed in a flavorful sesame sauce.",
			image: "16.webp",
			prepTime: 25,
			rating: 4.5,
			reviewCount: 85,
			reviews: [],
			servingSize: 2,
			vegan: true,
			vegetarian: true,
			mealTime: ["dinner"],
			cuisineType: ["Asian"],
			dishType: ["noodles", "stir-fry"],
			allergens: ["Soy", "Sesame", "Wheat"],
			nutritionalInfo: {
				calories: 460,
				fiber: 5,
				protein: 16,
				carbs: 60,
				fat: 15,
			},
			ingredients: [
				{ name: "noodles (wheat or rice)", quantity: "200", unit: "g" },
				{ name: "tofu (firm)", quantity: "150", unit: "g" },
				{ name: "sesame oil", quantity: "1", unit: "tbsp" },
				{ name: "soy sauce", quantity: "2", unit: "tbsp" },
				{ name: "sesame seeds", quantity: "1", unit: "tbsp" },
				{ name: "garlic", quantity: "2", unit: "cloves" },
				{ name: "ginger (fresh)", quantity: "1", unit: "tsp" },
				{ name: "green onion", quantity: "2", unit: "tbsp" },
				{ name: "vegetable oil", quantity: "1", unit: "tbsp" },
			],
			instructions: [
				"Cook noodles according to package instructions, then drain and rinse with cold water to prevent sticking.",
				"Drain tofu and cut into bite-sized cubes. Pat dry with a paper towel.",
				"Heat vegetable oil in a skillet or wok over medium-high heat. Fry tofu cubes until they are golden on all sides, then remove and set aside.",
				"In the same skillet, add minced garlic and grated ginger, cooking for about 30 seconds.",
				"Stir in sesame oil, soy sauce, and a splash of water to create a sauce. Add the cooked noodles, tossing to coat evenly.",
				"Return the tofu to the pan. Sprinkle sesame seeds and chopped green onion over everything, stirring well.",
				"Serve hot, adjusting seasonings to taste.",
			],
			tags: ["sesame", "noodles", "tofu"],
		},
		{
			id: "17",
			name: "Spinach Ricotta Stuffed Shells",
			description:
				"Savor the classic Italian flavors of our Spinach Ricotta Stuffed Shells, baked in a rich tomato sauce for a comforting and delicious meal.",
			image: "17.webp",
			prepTime: 45,
			rating: 4.6,
			reviewCount: 92,
			reviews: [],
			servingSize: 4,
			vegan: false,
			vegetarian: true,
			mealTime: ["dinner"],
			cuisineType: ["Italian"],
			dishType: ["pasta", "baked"],
			allergens: ["Milk", "Wheat", "Eggs"],
			nutritionalInfo: {
				calories: 520,
				fiber: 6,
				protein: 20,
				carbs: 65,
				fat: 22,
			},
			ingredients: [
				{ name: "jumbo pasta shells", quantity: "12", unit: "" },
				{ name: "ricotta cheese", quantity: "1", unit: "cup" },
				{ name: "spinach (fresh)", quantity: "2", unit: "cups" },
				{ name: "egg", quantity: "1", unit: "" },
				{ name: "parmesan cheese (grated)", quantity: "1/2", unit: "cup" },
				{ name: "tomato sauce", quantity: "1", unit: "cup" },
				{ name: "garlic powder", quantity: "1/2", unit: "tsp" },
				{ name: "salt", quantity: "1", unit: "tsp" },
				{ name: "black pepper", quantity: "1/2", unit: "tsp" },
			],
			instructions: [
				"Preheat oven to 375°F (190°C). Cook jumbo shells in salted boiling water until al dente, then drain.",
				"Chop spinach finely (you can sauté it for a minute to wilt) and combine with ricotta cheese, egg, parmesan cheese, garlic powder, salt, and pepper in a bowl.",
				"Spread a thin layer of tomato sauce in the bottom of a baking dish.",
				"Spoon the spinach-ricotta mixture into each shell and arrange them in the dish.",
				"Top with remaining tomato sauce.",
				"Cover with foil and bake for 20 minutes. Remove foil and bake for an additional 5-10 minutes until bubbly.",
				"Let rest for a few minutes before serving.",
			],
			tags: ["stuffed shells", "ricotta", "spinach"],
		},
		{
			id: "18",
			name: "Mushroom Barley Soup",
			description:
				"Warm up with our hearty Mushroom Barley Soup, a filling and flavorful dish that combines tender mushrooms with wholesome barley.",
			image: "18.webp",
			prepTime: 40,
			rating: 4.4,
			reviewCount: 80,
			reviews: [],
			servingSize: 4,
			vegan: true,
			vegetarian: true,
			mealTime: ["dinner"],
			cuisineType: ["American"],
			dishType: ["soup"],
			allergens: ["Mushroom", "Wheat"],
			nutritionalInfo: {
				calories: 380,
				fiber: 7,
				protein: 10,
				carbs: 55,
				fat: 10,
			},
			ingredients: [
				{ name: "pearl barley", quantity: "1", unit: "cup" },
				{ name: "mushrooms (sliced)", quantity: "200", unit: "g" },
				{ name: "onion (chopped)", quantity: "1/2", unit: "cup" },
				{ name: "celery (chopped)", quantity: "1/2", unit: "cup" },
				{ name: "carrot (chopped)", quantity: "1/2", unit: "cup" },
				{ name: "garlic", quantity: "2", unit: "cloves" },
				{ name: "vegetable broth", quantity: "6", unit: "cups" },
				{ name: "olive oil", quantity: "1", unit: "tbsp" },
				{ name: "salt", quantity: "1", unit: "tsp" },
				{ name: "black pepper", quantity: "1/2", unit: "tsp" },
			],
			instructions: [
				"Rinse pearl barley under cold water. Set aside.",
				"In a large pot, heat olive oil over medium heat. Sauté chopped onion, celery, and carrot for about 5 minutes until slightly softened.",
				"Add sliced mushrooms and minced garlic, cooking for an additional 3-4 minutes.",
				"Stir in the pearl barley. Pour in vegetable broth and bring to a boil.",
				"Reduce heat to low, cover, and simmer for 25-30 minutes, or until barley is tender.",
				"Season with salt and black pepper. Adjust flavors as desired.",
				"Serve hot, garnished with fresh parsley if you like.",
			],
			tags: ["mushroom", "barley", "soup"],
		},
		{
			id: "19",
			name: "Sweet Potato Black Bean Tacos",
			description:
				"Enjoy the vibrant flavors of our Sweet Potato Black Bean Tacos, where roasted sweet potatoes and hearty black beans create a delicious and satisfying meal.",
			image: "19.webp",
			prepTime: 25,
			rating: 4.5,
			reviewCount: 75,
			reviews: [],
			servingSize: 4,
			vegan: true,
			vegetarian: true,
			mealTime: ["dinner"],
			cuisineType: ["Mexican"],
			dishType: ["tacos"],
			allergens: [],
			nutritionalInfo: {
				calories: 400,
				fiber: 8,
				protein: 12,
				carbs: 55,
				fat: 10,
			},
			ingredients: [
				{ name: "sweet potato (diced)", quantity: "1", unit: "large" },
				{ name: "black beans (drained)", quantity: "1", unit: "can" },
				{ name: "olive oil", quantity: "1", unit: "tbsp" },
				{ name: "chili powder", quantity: "1", unit: "tsp" },
				{ name: "cumin", quantity: "1/2", unit: "tsp" },
				{ name: "salt", quantity: "1/2", unit: "tsp" },
				{ name: "corn tortillas", quantity: "8", unit: "" },
				{ name: "avocado (sliced)", quantity: "1", unit: "" },
				{ name: "lime", quantity: "1", unit: "" },
			],
			instructions: [
				"Preheat oven to 400°F (200°C). In a bowl, toss diced sweet potato with olive oil, chili powder, cumin, and salt.",
				"Spread the seasoned sweet potatoes on a baking sheet and roast for 15-20 minutes or until tender and slightly caramelized.",
				"Warm the black beans in a small saucepan over low heat. Season with a pinch of salt and pepper if desired.",
				"Heat corn tortillas in a skillet or microwave until soft and pliable.",
				"Fill each tortilla with roasted sweet potato and black beans.",
				"Top with sliced avocado and a squeeze of fresh lime juice.",
				"Serve with your favorite salsa or hot sauce on the side.",
			],
			tags: ["tacos", "sweet potato", "black bean"],
		},
		{
			id: "20",
			name: "Roasted Cauliflower and Apple Salad",
			description:
				"A refreshing Roasted Cauliflower and Apple Salad with a tangy dressing.",
			image: "20.webp",
			prepTime: 20,
			rating: 4.4,
			reviewCount: 70,
			reviews: [],
			servingSize: 2,
			vegan: true,
			vegetarian: true,
			mealTime: ["lunch"],
			cuisineType: ["American"],
			dishType: ["salad"],
			allergens: ["Apple"],
			nutritionalInfo: {
				calories: 350,
				fiber: 7,
				protein: 8,
				carbs: 45,
				fat: 12,
			},
			ingredients: [
				{ name: "cauliflower (florets)", quantity: "1", unit: "head" },
				{ name: "apple", quantity: "1", unit: "medium" },
				{ name: "mixed greens", quantity: "2", unit: "cups" },
				{ name: "olive oil", quantity: "2", unit: "tbsp" },
				{ name: "lemon juice", quantity: "1", unit: "tbsp" },
				{ name: "salt", quantity: "1/2", unit: "tsp" },
				{ name: "black pepper", quantity: "1/4", unit: "tsp" },
			],
			instructions: [
				"Preheat oven to 400°F (200°C). Separate the cauliflower into florets and toss with 1 tablespoon olive oil, salt, and pepper.",
				"Arrange florets on a baking sheet and roast for about 15-20 minutes until tender and slightly browned.",
				"Core and slice the apple into thin pieces. In a large salad bowl, place mixed greens and sliced apple.",
				"Whisk together the remaining 1 tablespoon olive oil with lemon juice, a pinch of salt, and pepper to make a dressing.",
				"Add the roasted cauliflower to the salad bowl. Pour the dressing over the salad and toss gently to combine.",
				"Serve immediately. Enjoy the contrasting flavors of sweet apple and earthy cauliflower.",
			],
			tags: ["salad", "cauliflower", "apple"],
		},
		{
			id: "21",
			name: "Vegan Cashew Cheese Spread",
			description:
				"A creamy Vegan Cashew Cheese Spread perfect for snacking or dipping.",
			image: "21.webp",
			prepTime: 15,
			rating: 4.7,
			reviewCount: 50,
			reviews: [],
			servingSize: 1,
			vegan: true,
			vegetarian: true,
			mealTime: ["snack"],
			cuisineType: ["Fusion"],
			dishType: ["spread"],
			allergens: ["Nuts"],
			nutritionalInfo: {
				calories: 300,
				fiber: 4,
				protein: 8,
				carbs: 20,
				fat: 22,
			},
			ingredients: [
				{ name: "cashews (raw)", quantity: "1", unit: "cup" },
				{ name: "lemon juice", quantity: "2", unit: "tbsp" },
				{ name: "nutritional yeast", quantity: "2", unit: "tbsp" },
				{ name: "garlic powder", quantity: "1/2", unit: "tsp" },
				{ name: "salt", quantity: "1/2", unit: "tsp" },
				{ name: "water", quantity: "1/4", unit: "cup" },
			],
			instructions: [
				"Soak cashews in water for at least 2 hours or overnight. Drain and rinse.",
				"Combine soaked cashews, lemon juice, nutritional yeast, garlic powder, salt, and 1/4 cup water in a blender or food processor.",
				"Blend until smooth, stopping to scrape down the sides as needed. Add more water if a thinner consistency is desired.",
				"Adjust salt or lemon juice to taste.",
				"Transfer to a serving bowl and chill for 30 minutes for flavors to meld.",
				"Serve with crackers, vegetable sticks, or as a sandwich spread.",
			],
			tags: ["vegan", "cashew", "spread"],
		},
		{
			id: "22",
			name: "Coconut Curry Lentils",
			description:
				"A warming Coconut Curry Lentils dish with rich and aromatic flavors.",
			image: "22.webp",
			prepTime: 35,
			rating: 4.5,
			reviewCount: 80,
			reviews: [],
			servingSize: 4,
			vegan: true,
			vegetarian: true,
			mealTime: ["dinner"],
			cuisineType: ["Indian"],
			dishType: ["curry", "stew"],
			allergens: [],
			nutritionalInfo: {
				calories: 380,
				fiber: 9,
				protein: 15,
				carbs: 50,
				fat: 14,
			},
			ingredients: [
				{ name: "lentils (dry)", quantity: "1", unit: "cup" },
				{ name: "coconut milk", quantity: "1", unit: "can" },
				{ name: "onion (chopped)", quantity: "1", unit: "small" },
				{ name: "curry powder", quantity: "1", unit: "tbsp" },
				{ name: "garlic", quantity: "2", unit: "cloves" },
				{ name: "ginger (fresh)", quantity: "1", unit: "tsp" },
				{ name: "vegetable broth", quantity: "2", unit: "cups" },
				{ name: "salt", quantity: "1", unit: "tsp" },
				{ name: "oil", quantity: "1", unit: "tbsp" },
			],
			instructions: [
				"Rinse lentils under cold water. Set aside.",
				"Heat oil in a pot over medium heat. Sauté chopped onion until translucent, about 4 minutes.",
				"Add minced garlic, grated ginger, and curry powder. Stir for 30 seconds to bloom the spices.",
				"Pour in coconut milk, vegetable broth, and the lentils.",
				"Bring to a gentle boil, then reduce heat and cover. Simmer for 20-25 minutes or until lentils are tender.",
				"Season with salt and adjust spices if desired.",
				"Serve with rice, naan, or as a standalone stew.",
			],
			tags: ["curry", "lentils", "coconut"],
		},
		{
			id: "23",
			name: "Blueberry Almond Overnight Oats",
			description:
				"Easy Blueberry Almond Overnight Oats for a quick and healthy breakfast.",
			image: "23.webp",
			prepTime: 10,
			rating: 4.8,
			reviewCount: 55,
			reviews: [],
			servingSize: 1,
			vegan: true,
			vegetarian: true,
			mealTime: ["breakfast"],
			cuisineType: ["American"],
			dishType: ["oats", "breakfast"],
			allergens: ["Nuts"],
			nutritionalInfo: {
				calories: 320,
				fiber: 6,
				protein: 10,
				carbs: 45,
				fat: 12,
			},
			ingredients: [
				{ name: "rolled oats", quantity: "1/2", unit: "cup" },
				{ name: "almond milk", quantity: "1/2", unit: "cup" },
				{ name: "blueberries", quantity: "1/2", unit: "cup" },
				{ name: "almond butter", quantity: "1", unit: "tbsp" },
				{ name: "chia seeds", quantity: "1", unit: "tsp" },
				{ name: "maple syrup (optional)", quantity: "1", unit: "tbsp" },
			],
			instructions: [
				"In a resealable container or mason jar, combine rolled oats, almond milk, chia seeds, and almond butter. Stir well.",
				"Add blueberries and maple syrup (if using) on top.",
				"Seal the container and refrigerate overnight (or at least 4 hours).",
				"In the morning, stir once more. If it's too thick, add a splash of almond milk.",
				"Enjoy cold or warm it up in the microwave for a minute or two.",
			],
			tags: ["overnight oats", "blueberry", "almond"],
		},
		{
			id: "24",
			name: "Vegetable Tempura",
			description:
				"Crispy Vegetable Tempura served with a light dipping sauce.",
			image: "24.webp",
			prepTime: 20,
			rating: 4.4,
			reviewCount: 60,
			reviews: [],
			servingSize: 3,
			vegan: false,
			vegetarian: true,
			mealTime: ["dinner"],
			cuisineType: ["Japanese"],
			dishType: ["tempura", "appetizer"],
			allergens: ["Wheat", "Eggs"],
			nutritionalInfo: {
				calories: 350,
				fiber: 4,
				protein: 9,
				carbs: 45,
				fat: 15,
			},
			ingredients: [
				{ name: "assorted vegetables", quantity: "2", unit: "cups" },
				{ name: "tempura batter mix", quantity: "1", unit: "cup" },
				{ name: "egg", quantity: "1", unit: "" },
				{ name: "ice-cold water", quantity: "3/4", unit: "cup" },
				{ name: "oil (for frying)", quantity: "", unit: "" },
				{ name: "salt", quantity: "1/2", unit: "tsp" },
			],
			instructions: [
				"Clean and chop vegetables into bite-sized pieces (e.g., carrots, bell peppers, zucchini). Pat them dry.",
				"Heat oil in a deep fryer or deep skillet to about 350°F (175°C).",
				"In a mixing bowl, whisk egg with ice-cold water. Gently stir in the tempura batter mix, being careful not to overmix (lumps are okay).",
				"Lightly dust vegetables with a little extra tempura mix or flour. Dip them into the batter, allowing excess to drip off.",
				"Carefully place the battered vegetables into the hot oil. Fry in small batches to avoid overcrowding.",
				"Fry for 2-3 minutes or until golden and crisp. Drain on paper towels. Sprinkle with salt if desired.",
				"Serve immediately with a light tempura dipping sauce or soy sauce.",
			],
			tags: ["tempura", "vegetables", "crispy"],
		},
		{
			id: "25",
			name: "Chili Lime Grilled Corn",
			description:
				"A zesty Chili Lime Grilled Corn that is perfect for a summer snack.",
			image: "25.webp",
			prepTime: 15,
			rating: 4.6,
			reviewCount: 65,
			reviews: [],
			servingSize: 2,
			vegan: true,
			vegetarian: true,
			mealTime: ["snack"],
			cuisineType: ["Mexican"],
			dishType: ["side", "grilled"],
			allergens: [],
			nutritionalInfo: {
				calories: 300,
				fiber: 5,
				protein: 8,
				carbs: 40,
				fat: 10,
			},
			ingredients: [
				{ name: "corn on the cob", quantity: "2", unit: "" },
				{ name: "chili powder", quantity: "1/2", unit: "tsp" },
				{ name: "lime", quantity: "1", unit: "" },
				{ name: "salt", quantity: "1/4", unit: "tsp" },
				{ name: "olive oil", quantity: "1", unit: "tbsp" },
			],
			instructions: [
				"Preheat grill to medium-high heat. Remove husks and silk from the corn.",
				"In a small bowl, mix olive oil, chili powder, and salt.",
				"Brush the seasoned oil mix over the corn cobs.",
				"Place corn on the grill, turning every 2-3 minutes, until lightly charred on all sides (about 10 minutes total).",
				"Remove from the grill and squeeze fresh lime juice over the corn.",
				"Serve immediately. Adjust chili powder or salt to taste.",
			],
			tags: ["grilled", "corn", "chili lime"],
		},
		{
			id: "26",
			name: "Peanut Butter Banana Smoothie",
			description:
				"A creamy Peanut Butter Banana Smoothie ideal for a quick breakfast.",
			image: "26.webp",
			prepTime: 5,
			rating: 4.7,
			reviewCount: 70,
			reviews: [],
			servingSize: 1,
			vegan: false,
			vegetarian: true,
			mealTime: ["breakfast"],
			cuisineType: ["American"],
			dishType: ["smoothie"],
			allergens: ["Nuts", "Milk"],
			nutritionalInfo: {
				calories: 350,
				fiber: 4,
				protein: 12,
				carbs: 45,
				fat: 15,
			},
			ingredients: [
				{ name: "banana", quantity: "1", unit: "large" },
				{ name: "peanut butter", quantity: "2", unit: "tbsp" },
				{ name: "milk (dairy or non-dairy)", quantity: "1", unit: "cup" },
				{ name: "ice cubes", quantity: "3", unit: "" },
				{ name: "honey (optional)", quantity: "1", unit: "tsp" },
			],
			instructions: [
				"Peel the banana and break it into chunks. Place it in a blender.",
				"Add peanut butter, milk, and ice cubes. If you prefer extra sweetness, add honey or a sweetener of your choice.",
				"Blend on high until the smoothie is thick and creamy.",
				"Pour into a glass and enjoy immediately.",
			],
			tags: ["smoothie", "peanut butter", "banana"],
		},
		{
			id: "27",
			name: "Avocado Toast with Sesame Seeds",
			description:
				"A trendy Avocado Toast topped with crunchy Sesame Seeds for extra flavor.",
			image: "27.webp",
			prepTime: 10,
			rating: 4.8,
			reviewCount: 80,
			reviews: [],
			servingSize: 1,
			vegan: true,
			vegetarian: true,
			mealTime: ["breakfast"],
			cuisineType: ["American"],
			dishType: ["toast", "breakfast"],
			allergens: ["Wheat", "Sesame"],
			nutritionalInfo: {
				calories: 300,
				fiber: 7,
				protein: 8,
				carbs: 40,
				fat: 14,
			},
			ingredients: [
				{ name: "whole grain bread", quantity: "1", unit: "slice" },
				{ name: "avocado", quantity: "1/2", unit: "" },
				{ name: "sesame seeds", quantity: "1", unit: "tsp" },
				{ name: "lemon juice", quantity: "1/2", unit: "tsp" },
				{ name: "salt", quantity: "1/4", unit: "tsp" },
				{ name: "red pepper flakes (optional)", quantity: "1/8", unit: "tsp" },
			],
			instructions: [
				"Lightly toast the slice of bread.",
				"In a small bowl, mash the avocado with lemon juice and salt.",
				"Spread the mashed avocado evenly on the warm toast.",
				"Sprinkle sesame seeds and red pepper flakes (if desired) on top.",
				"Serve immediately for the freshest taste and texture.",
			],
			tags: ["avocado", "toast", "sesame"],
		},
		{
			id: "28",
			name: "Lemon Herb Quinoa Salad",
			description:
				"A light and refreshing Lemon Herb Quinoa Salad ideal for lunch.",
			image: "28.webp",
			prepTime: 20,
			rating: 4.6,
			reviewCount: 55,
			reviews: [],
			servingSize: 2,
			vegan: true,
			vegetarian: true,
			mealTime: ["lunch"],
			cuisineType: ["American"],
			dishType: ["salad", "quinoa"],
			allergens: [],
			nutritionalInfo: {
				calories: 350,
				fiber: 6,
				protein: 10,
				carbs: 50,
				fat: 12,
			},
			ingredients: [
				{ name: "quinoa (cooked)", quantity: "1", unit: "cup" },
				{ name: "lemon juice", quantity: "1", unit: "tbsp" },
				{ name: "olive oil", quantity: "1", unit: "tbsp" },
				{ name: "fresh herbs (parsley, basil)", quantity: "1/4", unit: "cup" },
				{ name: "cherry tomatoes", quantity: "1/2", unit: "cup" },
				{ name: "cucumber (diced)", quantity: "1/2", unit: "cup" },
				{ name: "salt", quantity: "1/2", unit: "tsp" },
				{ name: "black pepper", quantity: "1/4", unit: "tsp" },
			],
			instructions: [
				"In a large bowl, combine the cooked quinoa, halved cherry tomatoes, diced cucumber, and chopped fresh herbs.",
				"In a small bowl, whisk together lemon juice, olive oil, salt, and black pepper.",
				"Pour the dressing over the quinoa mixture and toss well to combine.",
				"Adjust seasoning if needed. Chill for 10-15 minutes to allow flavors to develop.",
				"Serve as a light lunch or side dish.",
			],
			tags: ["quinoa", "salad", "lemon"],
		},
		{
			id: "29",
			name: "Butternut Squash Mac and Cheese",
			description:
				"A creamy Butternut Squash Mac and Cheese with a rich and savory flavor.",
			image: "29.webp",
			prepTime: 40,
			rating: 4.5,
			reviewCount: 90,
			reviews: [],
			servingSize: 3,
			vegan: false,
			vegetarian: true,
			mealTime: ["dinner"],
			cuisineType: ["American"],
			dishType: ["pasta", "casserole"],
			allergens: ["Milk", "Wheat"],
			nutritionalInfo: {
				calories: 550,
				fiber: 7,
				protein: 18,
				carbs: 60,
				fat: 25,
			},
			ingredients: [
				{ name: "macaroni pasta", quantity: "2", unit: "cups" },
				{ name: "butternut squash (cubed)", quantity: "2", unit: "cups" },
				{ name: "milk", quantity: "1", unit: "cup" },
				{ name: "cheddar cheese (shredded)", quantity: "1", unit: "cup" },
				{ name: "butter", quantity: "2", unit: "tbsp" },
				{ name: "flour (all-purpose)", quantity: "2", unit: "tbsp" },
				{ name: "salt", quantity: "1", unit: "tsp" },
				{ name: "black pepper", quantity: "1/2", unit: "tsp" },
			],
			instructions: [
				"Cook macaroni in a pot of salted boiling water until al dente. Drain and set aside.",
				"In a separate pot, boil or steam the cubed butternut squash until very tender, about 10-12 minutes. Drain and puree until smooth.",
				"In a saucepan, melt butter over medium heat. Whisk in flour to form a roux, cooking for 1 minute.",
				"Slowly pour in milk, whisking constantly to prevent lumps. Simmer until it begins to thicken.",
				"Stir in the butternut squash puree and shredded cheddar cheese until the cheese is melted. Season with salt and black pepper.",
				"Mix the sauce with the cooked macaroni. Transfer to a baking dish if desired and broil for a few minutes for a bubbly top.",
				"Serve hot and enjoy the comforting flavors.",
			],
			tags: ["mac and cheese", "butternut squash", "comfort food"],
		},
		{
			id: "30",
			name: "Savory Carrot and Lentil Patties",
			description:
				"Hearty Savory Carrot and Lentil Patties that work well as a main or side dish.",
			image: "30.webp",
			prepTime: 25,
			rating: 4.4,
			reviewCount: 60,
			reviews: [],
			servingSize: 4,
			vegan: true,
			vegetarian: true,
			mealTime: ["dinner"],
			cuisineType: ["Fusion"],
			dishType: ["patties", "veggie burger"],
			allergens: ["Carrot"],
			nutritionalInfo: {
				calories: 400,
				fiber: 8,
				protein: 14,
				carbs: 50,
				fat: 10,
			},
			ingredients: [
				{ name: "carrots (grated)", quantity: "1", unit: "cup" },
				{ name: "lentils (cooked)", quantity: "1", unit: "cup" },
				{ name: "onion (chopped)", quantity: "1/4", unit: "cup" },
				{ name: "flour (or breadcrumbs)", quantity: "1/2", unit: "cup" },
				{ name: "cumin", quantity: "1", unit: "tsp" },
				{ name: "salt", quantity: "1/2", unit: "tsp" },
				{ name: "black pepper", quantity: "1/4", unit: "tsp" },
				{ name: "oil (for frying)", quantity: "", unit: "" },
			],
			instructions: [
				"In a large bowl, mash cooked lentils with a fork or potato masher.",
				"Stir in grated carrots, chopped onion, flour (or breadcrumbs), cumin, salt, and black pepper.",
				"Mix until a moldable dough forms. If too dry, add a tablespoon of water. If too wet, add more flour.",
				"Shape the mixture into patties of desired size.",
				"Heat a thin layer of oil in a skillet over medium heat. Cook patties for 3-4 minutes on each side until golden brown.",
				"Drain on paper towels and serve with a dipping sauce or in a bun as a veggie burger.",
			],
			tags: ["patties", "carrot", "lentil"],
		},
		{
			id: "31",
			name: "Walnut Pesto Pasta",
			description:
				"A flavorful Walnut Pesto Pasta offering a twist on the classic dish.",
			image: "31.webp",
			prepTime: 30,
			rating: 4.6,
			reviewCount: 85,
			reviews: [],
			servingSize: 3,
			vegan: false,
			vegetarian: true,
			mealTime: ["dinner"],
			cuisineType: ["Italian"],
			dishType: ["pasta", "main"],
			allergens: ["Nuts", "Milk", "Wheat"],
			nutritionalInfo: {
				calories: 500,
				fiber: 5,
				protein: 16,
				carbs: 60,
				fat: 22,
			},
			ingredients: [
				{ name: "pasta (penne or fusilli)", quantity: "200", unit: "g" },
				{ name: "walnuts", quantity: "1/2", unit: "cup" },
				{ name: "basil (fresh)", quantity: "1", unit: "cup" },
				{ name: "parmesan cheese", quantity: "1/2", unit: "cup" },
				{ name: "garlic", quantity: "2", unit: "cloves" },
				{ name: "olive oil", quantity: "1/4", unit: "cup" },
				{ name: "salt", quantity: "1/2", unit: "tsp" },
				{ name: "black pepper", quantity: "1/4", unit: "tsp" },
			],
			instructions: [
				"Cook the pasta in salted boiling water according to package instructions. Reserve 1/4 cup of pasta water before draining.",
				"In a food processor, combine walnuts, basil, parmesan cheese, and garlic. Pulse until roughly chopped.",
				"Slowly drizzle in the olive oil while pulsing to achieve a pesto consistency. Add pasta water as needed to thin the sauce.",
				"Season with salt and black pepper to taste.",
				"Toss the drained pasta with the walnut pesto. Adjust seasoning if necessary.",
				"Serve immediately, garnished with additional grated parmesan or chopped walnuts.",
			],
			tags: ["pesto", "walnut", "pasta"],
		},
		{
			id: "32",
			name: "Chocolate Chip Zucchini Bread",
			description:
				"Moist Chocolate Chip Zucchini Bread perfect for a snack or breakfast.",
			image: "32.webp",
			prepTime: 35,
			rating: 4.5,
			reviewCount: 75,
			reviews: [],
			servingSize: 1,
			vegan: false,
			vegetarian: true,
			mealTime: ["snack"],
			cuisineType: ["American"],
			dishType: ["bread", "baked"],
			allergens: ["Wheat", "Eggs", "Milk"],
			nutritionalInfo: {
				calories: 420,
				fiber: 4,
				protein: 8,
				carbs: 55,
				fat: 18,
			},
			ingredients: [
				{ name: "zucchini (grated)", quantity: "1", unit: "cup" },
				{ name: "all-purpose flour", quantity: "1.5", unit: "cups" },
				{ name: "sugar", quantity: "1/2", unit: "cup" },
				{ name: "egg", quantity: "1", unit: "" },
				{ name: "milk", quantity: "1/2", unit: "cup" },
				{ name: "chocolate chips", quantity: "1/2", unit: "cup" },
				{ name: "baking soda", quantity: "1", unit: "tsp" },
				{ name: "cinnamon", quantity: "1", unit: "tsp" },
				{ name: "salt", quantity: "1/4", unit: "tsp" },
				{ name: "vegetable oil", quantity: "2", unit: "tbsp" },
			],
			instructions: [
				"Preheat oven to 350°F (175°C). Grease a loaf pan or line with parchment paper.",
				"In a medium bowl, whisk together flour, sugar, baking soda, cinnamon, and salt.",
				"In a separate bowl, beat the egg with milk and vegetable oil. Stir in grated zucchini.",
				"Combine the wet and dry ingredients, mixing gently until just combined. Fold in chocolate chips.",
				"Pour the batter into the prepared loaf pan, smoothing the top.",
				"Bake for 45-50 minutes or until a toothpick inserted in the center comes out clean.",
				"Let the bread cool in the pan for 10 minutes before transferring to a wire rack to cool completely.",
			],
			tags: ["zucchini bread", "chocolate chip", "baked"],
		},
		{
			id: "33",
			name: "Apple Walnut Salad",
			description: "A fresh Apple Walnut Salad tossed in a tangy vinaigrette.",
			image: "33.webp",
			prepTime: 15,
			rating: 4.7,
			reviewCount: 60,
			reviews: [],
			servingSize: 2,
			vegan: true,
			vegetarian: true,
			mealTime: ["lunch"],
			cuisineType: ["American"],
			dishType: ["salad"],
			allergens: ["Apple", "Nuts"],
			nutritionalInfo: {
				calories: 320,
				fiber: 6,
				protein: 8,
				carbs: 40,
				fat: 14,
			},
			ingredients: [
				{ name: "apple (sliced)", quantity: "1", unit: "medium" },
				{ name: "mixed greens", quantity: "2", unit: "cups" },
				{ name: "walnuts (chopped)", quantity: "1/4", unit: "cup" },
				{ name: "olive oil", quantity: "2", unit: "tbsp" },
				{ name: "balsamic vinegar", quantity: "1", unit: "tbsp" },
				{ name: "salt", quantity: "1/4", unit: "tsp" },
				{ name: "black pepper", quantity: "1/8", unit: "tsp" },
			],
			instructions: [
				"Rinse and dry mixed greens. Place them in a large salad bowl.",
				"Thinly slice the apple and add to the greens.",
				"Sprinkle chopped walnuts over the top.",
				"In a small bowl, whisk together olive oil, balsamic vinegar, salt, and pepper to form a dressing.",
				"Drizzle the dressing over the salad and toss gently to coat.",
				"Serve immediately for the freshest flavor and texture.",
			],
			tags: ["apple", "salad", "walnut"],
		},
		{
			id: "34",
			name: "Eggplant Chickpea Tagine",
			description: "A flavorful Eggplant Chickpea Tagine with aromatic spices.",
			image: "34.webp",
			prepTime: 45,
			rating: 4.5,
			reviewCount: 70,
			reviews: [],
			servingSize: 4,
			vegan: true,
			vegetarian: true,
			mealTime: ["dinner"],
			cuisineType: ["Moroccan"],
			dishType: ["stew", "tagine"],
			allergens: [],
			nutritionalInfo: {
				calories: 420,
				fiber: 9,
				protein: 15,
				carbs: 55,
				fat: 14,
			},
			ingredients: [
				{ name: "eggplant (diced)", quantity: "1", unit: "medium" },
				{ name: "chickpeas (canned)", quantity: "1", unit: "can" },
				{ name: "tomatoes (diced)", quantity: "1", unit: "cup" },
				{ name: "onion (chopped)", quantity: "1/2", unit: "cup" },
				{ name: "garlic", quantity: "2", unit: "cloves" },
				{
					name: "ras el hanout (or Moroccan spice blend)",
					quantity: "1",
					unit: "tbsp",
				},
				{ name: "vegetable broth", quantity: "1", unit: "cup" },
				{ name: "olive oil", quantity: "2", unit: "tbsp" },
				{ name: "salt", quantity: "1", unit: "tsp" },
				{ name: "black pepper", quantity: "1/2", unit: "tsp" },
			],
			instructions: [
				"Heat olive oil in a tagine or large pot over medium heat. Add chopped onion and sauté until translucent, about 5 minutes.",
				"Add minced garlic and diced eggplant, cooking for another 4-5 minutes until eggplant begins to soften.",
				"Stir in the ras el hanout (or Moroccan spice blend) and diced tomatoes.",
				"Add drained chickpeas and vegetable broth. Stir to combine.",
				"Cover and simmer for 20-25 minutes until eggplant is tender and flavors meld.",
				"Season with salt and black pepper. Taste and adjust spices as needed.",
				"Serve with couscous or flatbread for a complete meal.",
			],
			tags: ["tagine", "eggplant", "chickpea"],
		},
		{
			id: "35",
			name: "Pumpkin Spice Latte",
			description: "A warm and cozy Pumpkin Spice Latte perfect for autumn.",
			image: "35.webp",
			prepTime: 10,
			rating: 4.8,
			reviewCount: 80,
			reviews: [],
			servingSize: 1,
			vegan: false,
			vegetarian: true,
			mealTime: ["snack"],
			cuisineType: ["American"],
			dishType: ["beverage"],
			allergens: ["Milk"],
			nutritionalInfo: {
				calories: 250,
				fiber: 2,
				protein: 6,
				carbs: 30,
				fat: 10,
			},
			ingredients: [
				{ name: "pumpkin puree", quantity: "1/2", unit: "cup" },
				{ name: "milk", quantity: "1", unit: "cup" },
				{ name: "pumpkin pie spice", quantity: "1", unit: "tsp" },
				{ name: "coffee (strong brewed)", quantity: "1/2", unit: "cup" },
				{ name: "sugar (or sweetener)", quantity: "1", unit: "tbsp" },
				{ name: "vanilla extract (optional)", quantity: "1/2", unit: "tsp" },
			],
			instructions: [
				"In a small saucepan, whisk together pumpkin puree, milk, pumpkin pie spice, and sugar over medium heat.",
				"Heat until hot but not boiling, stirring frequently to avoid scorching.",
				"Remove from heat and stir in vanilla extract if desired.",
				"Brew a strong cup of coffee or espresso.",
				"Pour the pumpkin-milk mixture into a mug, then slowly add the coffee. Stir gently.",
				"Top with whipped cream (optional) and a sprinkle of pumpkin pie spice for garnish.",
			],
			tags: ["latte", "pumpkin spice", "autumn"],
		},
		{
			id: "36",
			name: "Sesame Crusted Tofu Bites",
			description:
				"Crunchy Sesame Crusted Tofu Bites perfect as an appetizer or snack.",
			image: "36.webp",
			prepTime: 20,
			rating: 4.5,
			reviewCount: 65,
			reviews: [],
			servingSize: 2,
			vegan: true,
			vegetarian: true,
			mealTime: ["snack"],
			cuisineType: ["Asian"],
			dishType: ["appetizer", "tofu"],
			allergens: ["Soy", "Sesame"],
			nutritionalInfo: {
				calories: 350,
				fiber: 5,
				protein: 16,
				carbs: 30,
				fat: 18,
			},
			ingredients: [
				{ name: "firm tofu", quantity: "200", unit: "g" },
				{ name: "soy sauce", quantity: "2", unit: "tbsp" },
				{ name: "sesame seeds", quantity: "2", unit: "tbsp" },
				{ name: "cornstarch", quantity: "1", unit: "tbsp" },
				{ name: "garlic powder", quantity: "1/2", unit: "tsp" },
				{ name: "oil (for baking or frying)", quantity: "", unit: "" },
			],
			instructions: [
				"Drain tofu and press out excess moisture. Cut into bite-sized cubes.",
				"In a bowl, mix soy sauce, cornstarch, and garlic powder to form a light marinade.",
				"Toss tofu cubes in the marinade, ensuring they are evenly coated.",
				"Sprinkle sesame seeds over the tofu, pressing gently to adhere.",
				"Choose to bake at 400°F (200°C) for 15-20 minutes (turning halfway) or pan-fry in a little oil until golden on all sides.",
				"Serve hot with a dipping sauce, such as sweet chili or soy sauce.",
			],
			tags: ["tofu bites", "sesame", "appetizer"],
		},
		{
			id: "37",
			name: "Homemade Mushroom Pizza",
			description:
				"A delightful Homemade Mushroom Pizza with a crispy crust and rich toppings.",
			image: "37.webp",
			prepTime: 30,
			rating: 4.6,
			reviewCount: 90,
			reviews: [],
			servingSize: 3,
			vegan: false,
			vegetarian: true,
			mealTime: ["dinner"],
			cuisineType: ["Italian"],
			dishType: ["pizza", "main"],
			allergens: ["Milk", "Wheat", "Mushroom"],
			nutritionalInfo: {
				calories: 550,
				fiber: 6,
				protein: 20,
				carbs: 70,
				fat: 22,
			},
			ingredients: [
				{ name: "pizza dough", quantity: "1", unit: "ball" },
				{ name: "tomato sauce", quantity: "1/2", unit: "cup" },
				{ name: "mozzarella cheese", quantity: "1", unit: "cup" },
				{ name: "mushrooms (sliced)", quantity: "200", unit: "g" },
				{ name: "olive oil", quantity: "1", unit: "tbsp" },
				{ name: "salt", quantity: "1/4", unit: "tsp" },
				{ name: "black pepper", quantity: "1/4", unit: "tsp" },
			],
			instructions: [
				"Preheat your oven to 475°F (245°C) or according to dough instructions. If using a pizza stone, place it in the oven to preheat.",
				"Roll out the pizza dough to your desired thickness on a lightly floured surface.",
				"Spread tomato sauce evenly over the dough, leaving a small border for the crust.",
				"Heat olive oil in a pan over medium heat and sauté sliced mushrooms with salt and pepper for 3-4 minutes, just to release moisture.",
				"Distribute sautéed mushrooms over the sauce, then sprinkle with mozzarella cheese.",
				"Carefully transfer the pizza to the preheated oven or pizza stone. Bake for 10-12 minutes, or until the crust is golden and cheese is bubbly.",
				"Slice and serve hot, garnished with fresh herbs if you like.",
			],
			tags: ["pizza", "mushroom", "homemade"],
		},
		{
			id: "38",
			name: "Crispy Cauliflower Wings",
			description:
				"Crispy Cauliflower Wings with a spicy dipping sauce for a vegan-friendly appetizer.",
			image: "38.webp",
			prepTime: 25,
			rating: 4.5,
			reviewCount: 70,
			reviews: [],
			servingSize: 2,
			vegan: true,
			vegetarian: true,
			mealTime: ["snack"],
			cuisineType: ["American"],
			dishType: ["appetizer", "wings"],
			allergens: ["Wheat"],
			nutritionalInfo: {
				calories: 320,
				fiber: 5,
				protein: 8,
				carbs: 40,
				fat: 12,
			},
			ingredients: [
				{ name: "cauliflower (florets)", quantity: "1", unit: "head" },
				{ name: "all-purpose flour", quantity: "1/2", unit: "cup" },
				{ name: "water", quantity: "1/2", unit: "cup" },
				{ name: "garlic powder", quantity: "1/2", unit: "tsp" },
				{ name: "paprika", quantity: "1/2", unit: "tsp" },
				{ name: "salt", quantity: "1/2", unit: "tsp" },
				{ name: "hot sauce (optional)", quantity: "2", unit: "tbsp" },
			],
			instructions: [
				"Preheat oven to 425°F (220°C). Line a baking sheet with parchment paper.",
				"Cut cauliflower into bite-sized florets. In a bowl, whisk together flour, water, garlic powder, paprika, and salt to form a batter.",
				"Dip each cauliflower floret into the batter, letting excess drip off. Place on the baking sheet in a single layer.",
				"Bake for 20 minutes, flipping halfway through.",
				"If you want them spicy, brush hot sauce on the florets after 20 minutes, then return to the oven for an additional 5-10 minutes.",
				"Remove from the oven and serve hot with your favorite dipping sauce.",
			],
			tags: ["cauliflower", "wings", "crispy"],
		},
		{
			id: "39",
			name: "Spiced Apple Chia Pudding",
			description:
				"A delightful Spiced Apple Chia Pudding perfect for a nutritious dessert.",
			image: "39.webp",
			prepTime: 10,
			rating: 4.7,
			reviewCount: 60,
			reviews: [],
			servingSize: 1,
			vegan: true,
			vegetarian: true,
			mealTime: ["dessert"],
			cuisineType: ["American"],
			dishType: ["pudding", "dessert"],
			allergens: ["Apple"],
			nutritionalInfo: {
				calories: 280,
				fiber: 7,
				protein: 6,
				carbs: 35,
				fat: 10,
			},
			ingredients: [
				{ name: "chia seeds", quantity: "3", unit: "tbsp" },
				{ name: "non-dairy milk", quantity: "1", unit: "cup" },
				{ name: "apple (chopped)", quantity: "1/2", unit: "cup" },
				{ name: "cinnamon", quantity: "1/2", unit: "tsp" },
				{ name: "nutmeg (optional)", quantity: "1/8", unit: "tsp" },
				{ name: "maple syrup", quantity: "1", unit: "tbsp" },
			],
			instructions: [
				"In a jar or small bowl, combine chia seeds, non-dairy milk, cinnamon, nutmeg, and maple syrup. Stir well.",
				"Let the mixture sit for about 5 minutes, then stir again to break up any clumps.",
				"Cover and refrigerate for at least 2 hours or overnight, until pudding-like in consistency.",
				"Meanwhile, lightly sauté the chopped apple with a pinch of cinnamon (optional) to soften, or use raw if you prefer.",
				"Top the chia pudding with the prepared apples.",
				"Serve chilled for a wholesome dessert or snack.",
			],
			tags: ["chia pudding", "apple", "spiced"],
		},
		{
			id: "40",
			name: "Sweet Potato Peanut Stew",
			description:
				"A hearty Sweet Potato Peanut Stew with a rich and creamy texture.",
			image: "40.webp",
			prepTime: 40,
			rating: 4.5,
			reviewCount: 75,
			reviews: [],
			servingSize: 4,
			vegan: true,
			vegetarian: true,
			mealTime: ["dinner"],
			cuisineType: ["African"],
			dishType: ["stew"],
			allergens: ["Nuts"],
			nutritionalInfo: {
				calories: 420,
				fiber: 8,
				protein: 16,
				carbs: 55,
				fat: 20,
			},
			ingredients: [
				{
					name: "sweet potatoes (peeled & diced)",
					quantity: "2",
					unit: "medium",
				},
				{ name: "peanut butter", quantity: "2", unit: "tbsp" },
				{ name: "onion (chopped)", quantity: "1/2", unit: "cup" },
				{ name: "garlic", quantity: "2", unit: "cloves" },
				{ name: "tomato paste", quantity: "1", unit: "tbsp" },
				{ name: "vegetable broth", quantity: "3", unit: "cups" },
				{ name: "cumin", quantity: "1", unit: "tsp" },
				{ name: "red pepper flakes (optional)", quantity: "1/4", unit: "tsp" },
				{ name: "salt", quantity: "1", unit: "tsp" },
				{ name: "oil", quantity: "1", unit: "tbsp" },
			],
			instructions: [
				"Heat oil in a pot over medium heat. Sauté chopped onion for 3-4 minutes until softened.",
				"Add minced garlic, tomato paste, cumin, and red pepper flakes (if using). Stir for 1 minute.",
				"Stir in diced sweet potatoes. Pour in the vegetable broth and bring to a simmer.",
				"Cover and cook for about 15-20 minutes, or until sweet potatoes are fork-tender.",
				"Lower the heat and stir in peanut butter until fully dissolved and the stew thickens.",
				"Season with salt. Adjust thickness by adding more broth if needed.",
				"Serve hot, garnished with chopped peanuts or fresh herbs if desired.",
			],
			tags: ["stew", "sweet potato", "peanut"],
		},
		{
			id: "41",
			name: "Cheesy Garlic Bread",
			description: "A classic Cheesy Garlic Bread perfect as a side or snack.",
			image: "41.webp",
			prepTime: 15,
			rating: 4.6,
			reviewCount: 80,
			reviews: [],
			servingSize: 4,
			vegan: false,
			vegetarian: true,
			mealTime: ["snack"],
			cuisineType: ["Italian"],
			dishType: ["bread", "side"],
			allergens: ["Milk", "Wheat"],
			nutritionalInfo: {
				calories: 400,
				fiber: 3,
				protein: 10,
				carbs: 50,
				fat: 18,
			},
			ingredients: [
				{ name: "baguette", quantity: "1", unit: "large" },
				{ name: "butter (softened)", quantity: "3", unit: "tbsp" },
				{ name: "garlic (minced)", quantity: "2", unit: "cloves" },
				{ name: "parsley (chopped)", quantity: "1", unit: "tbsp" },
				{ name: "mozzarella cheese (shredded)", quantity: "1", unit: "cup" },
				{ name: "salt", quantity: "1/4", unit: "tsp" },
			],
			instructions: [
				"Preheat oven to 400°F (200°C). Slice the baguette lengthwise.",
				"In a small bowl, combine softened butter, minced garlic, chopped parsley, and a pinch of salt.",
				"Spread the garlic butter evenly on the cut sides of the baguette.",
				"Top with shredded mozzarella cheese.",
				"Place on a baking sheet and bake for 8-10 minutes until the cheese is melted and the edges of the bread are golden.",
				"Slice and serve hot.",
			],
			tags: ["garlic bread", "cheesy", "side"],
		},
		{
			id: "42",
			name: "Ratatouille",
			description:
				"A classic French Ratatouille bursting with fresh vegetables and herbs.",
			image: "42.webp",
			prepTime: 50,
			rating: 4.7,
			reviewCount: 85,
			reviews: [],
			servingSize: 4,
			vegan: true,
			vegetarian: true,
			mealTime: ["dinner"],
			cuisineType: ["French"],
			dishType: ["stew", "vegetable"],
			allergens: [],
			nutritionalInfo: {
				calories: 350,
				fiber: 8,
				protein: 8,
				carbs: 45,
				fat: 12,
			},
			ingredients: [
				{ name: "eggplant (diced)", quantity: "1", unit: "medium" },
				{ name: "zucchini (sliced)", quantity: "1", unit: "medium" },
				{ name: "bell pepper (chopped)", quantity: "1", unit: "large" },
				{ name: "onion (chopped)", quantity: "1", unit: "small" },
				{ name: "tomatoes (crushed)", quantity: "1", unit: "cup" },
				{ name: "garlic", quantity: "2", unit: "cloves" },
				{ name: "herbes de provence", quantity: "1", unit: "tsp" },
				{ name: "olive oil", quantity: "2", unit: "tbsp" },
				{ name: "salt", quantity: "1", unit: "tsp" },
				{ name: "black pepper", quantity: "1/2", unit: "tsp" },
			],
			instructions: [
				"Heat olive oil in a large pot over medium heat. Sauté chopped onion and minced garlic for 3-4 minutes.",
				"Add diced eggplant and bell pepper. Cook until they begin to soften, about 5-6 minutes.",
				"Stir in sliced zucchini, crushed tomatoes, herbes de provence, salt, and pepper.",
				"Cover and simmer for 15-20 minutes, stirring occasionally, until vegetables are tender.",
				"For extra flavor, drizzle a little more olive oil and a splash of lemon juice over the finished dish.",
				"Adjust seasoning to taste. Serve hot with crusty bread or as a side to your favorite protein.",
			],
			tags: ["ratatouille", "french", "vegetables"],
		},
		{
			id: "43",
			name: "Carrot Ginger Dressing Salad",
			description:
				"A vibrant salad featuring mixed greens with a Carrot Ginger Dressing.",
			image: "43.webp",
			prepTime: 15,
			rating: 4.5,
			reviewCount: 70,
			reviews: [],
			servingSize: 2,
			vegan: true,
			vegetarian: true,
			mealTime: ["lunch"],
			cuisineType: ["American"],
			dishType: ["salad"],
			allergens: ["Carrot"],
			nutritionalInfo: {
				calories: 300,
				fiber: 5,
				protein: 7,
				carbs: 40,
				fat: 10,
			},
			ingredients: [
				{ name: "mixed greens", quantity: "2", unit: "cups" },
				{ name: "carrot (chopped)", quantity: "1", unit: "medium" },
				{ name: "ginger (fresh)", quantity: "1", unit: "tsp" },
				{ name: "rice vinegar", quantity: "2", unit: "tbsp" },
				{ name: "soy sauce", quantity: "1", unit: "tbsp" },
				{ name: "sesame oil", quantity: "1", unit: "tsp" },
				{ name: "honey or maple syrup", quantity: "1", unit: "tsp" },
				{ name: "salt", quantity: "1/4", unit: "tsp" },
			],
			instructions: [
				"Add chopped carrot, grated ginger, rice vinegar, soy sauce, sesame oil, honey (or maple syrup), and salt to a blender or food processor.",
				"Blend until smooth and creamy. Add a tablespoon of water if needed to achieve desired consistency.",
				"Place mixed greens in a large salad bowl.",
				"Drizzle the carrot ginger dressing over the greens.",
				"Toss gently to coat the leaves. Add a splash of lemon juice for extra brightness if desired.",
				"Serve immediately, garnishing with sesame seeds or chopped nuts, if you like.",
			],
			tags: ["salad", "carrot", "ginger"],
		},
		{
			id: "44",
			name: "Mushroom and Spinach Quiche",
			description: "A savory Mushroom and Spinach Quiche with a flaky crust.",
			image: "44.webp",
			prepTime: 50,
			rating: 4.6,
			reviewCount: 90,
			reviews: [],
			servingSize: 4,
			vegan: false,
			vegetarian: true,
			mealTime: ["dinner"],
			cuisineType: ["French"],
			dishType: ["quiche", "baked"],
			allergens: ["Milk", "Eggs", "Wheat", "Mushroom"],
			nutritionalInfo: {
				calories: 500,
				fiber: 4,
				protein: 20,
				carbs: 55,
				fat: 25,
			},
			ingredients: [
				{ name: "pie crust", quantity: "1", unit: "" },
				{ name: "mushrooms (sliced)", quantity: "150", unit: "g" },
				{ name: "spinach (fresh)", quantity: "2", unit: "cups" },
				{ name: "eggs", quantity: "3", unit: "" },
				{ name: "milk", quantity: "1/2", unit: "cup" },
				{ name: "cheddar cheese (shredded)", quantity: "1/2", unit: "cup" },
				{ name: "salt", quantity: "1/2", unit: "tsp" },
				{ name: "black pepper", quantity: "1/4", unit: "tsp" },
				{ name: "olive oil", quantity: "1", unit: "tbsp" },
			],
			instructions: [
				"Preheat oven to 375°F (190°C). Roll out or prepare the pie crust in a quiche dish or pie pan.",
				"In a skillet, heat olive oil over medium heat. Sauté sliced mushrooms until they release moisture and brown slightly, about 5 minutes.",
				"Add spinach and cook until wilted, about 1 minute. Remove from heat and let cool slightly.",
				"In a bowl, whisk together eggs, milk, salt, and black pepper.",
				"Spread the mushroom-spinach mixture evenly in the pie crust. Sprinkle shredded cheddar cheese on top.",
				"Pour the egg mixture over the fillings, ensuring everything is well distributed.",
				"Bake for 30-35 minutes or until the center is set and the crust is golden. Let rest for 5 minutes before slicing.",
			],
			tags: ["quiche", "mushroom", "spinach"],
		},
		{
			id: "45",
			name: "Roasted Brussels Sprouts with Almonds",
			description:
				"A healthy side dish of Roasted Brussels Sprouts topped with crunchy almonds.",
			image: "45.webp",
			prepTime: 25,
			rating: 4.5,
			reviewCount: 70,
			reviews: [],
			servingSize: 2,
			vegan: true,
			vegetarian: true,
			mealTime: ["dinner"],
			cuisineType: ["American"],
			dishType: ["side", "roasted"],
			allergens: ["Nuts"],
			nutritionalInfo: {
				calories: 320,
				fiber: 6,
				protein: 8,
				carbs: 35,
				fat: 15,
			},
			ingredients: [
				{ name: "Brussels sprouts", quantity: "1", unit: "lb" },
				{ name: "olive oil", quantity: "1", unit: "tbsp" },
				{ name: "salt", quantity: "1/2", unit: "tsp" },
				{ name: "black pepper", quantity: "1/4", unit: "tsp" },
				{ name: "almonds (sliced or slivered)", quantity: "1/4", unit: "cup" },
				{ name: "balsamic vinegar (optional)", quantity: "1", unit: "tbsp" },
			],
			instructions: [
				"Preheat oven to 400°F (200°C). Trim the ends of the Brussels sprouts and cut them in half if large.",
				"Toss sprouts with olive oil, salt, and pepper on a baking sheet.",
				"Roast for 15-20 minutes, stirring halfway, until golden and slightly crispy.",
				"Sprinkle sliced almonds on top and return to the oven for an additional 3-5 minutes to toast the almonds lightly.",
				"Drizzle with balsamic vinegar if desired before serving.",
				"Serve hot as a side dish or toss into a salad for extra crunch.",
			],
			tags: ["brussels sprouts", "roasted", "almonds"],
		},
		{
			id: "46",
			name: "Vegetable Sushi Rolls",
			description:
				"Delicious Vegetable Sushi Rolls perfect for a light lunch or snack.",
			image: "46.webp",
			prepTime: 30,
			rating: 4.6,
			reviewCount: 80,
			reviews: [],
			servingSize: 2,
			vegan: true,
			vegetarian: true,
			mealTime: ["lunch"],
			cuisineType: ["Japanese"],
			dishType: ["sushi", "rolls"],
			allergens: ["Soy", "Sesame", "Wheat"],
			nutritionalInfo: {
				calories: 350,
				fiber: 5,
				protein: 10,
				carbs: 50,
				fat: 8,
			},
			ingredients: [
				{ name: "sushi rice (cooked)", quantity: "1", unit: "cup" },
				{ name: "nori sheets", quantity: "4", unit: "" },
				{ name: "cucumber (julienned)", quantity: "1/2", unit: "cup" },
				{ name: "carrot (julienned)", quantity: "1/2", unit: "cup" },
				{ name: "avocado (sliced)", quantity: "1/2", unit: "" },
				{ name: "rice vinegar", quantity: "1", unit: "tbsp" },
				{ name: "sesame seeds", quantity: "1", unit: "tbsp" },
				{ name: "soy sauce (for dipping)", quantity: "", unit: "" },
			],
			instructions: [
				"Season the cooked sushi rice with rice vinegar (and a pinch of sugar if desired). Let it cool slightly.",
				"Lay a nori sheet on a bamboo sushi mat (shiny side down). Spread a thin layer of sushi rice evenly, leaving a 1-inch border at the top.",
				"Arrange cucumber, carrot, and avocado in a line near the bottom edge of the rice.",
				"Roll the sushi tightly away from you, using the mat to apply gentle pressure. Moisten the top border with water to seal.",
				"Slice each roll into 6-8 pieces. Sprinkle sesame seeds on top if desired.",
				"Serve with soy sauce, wasabi, and pickled ginger.",
			],
			tags: ["sushi", "vegetable", "rolls"],
		},
		{
			id: "47",
			name: "Coconut Chia Pudding",
			description:
				"A refreshing Coconut Chia Pudding that's perfect for a healthy dessert.",
			image: "47.webp",
			prepTime: 10,
			rating: 4.7,
			reviewCount: 50,
			reviews: [],
			servingSize: 1,
			vegan: true,
			vegetarian: true,
			mealTime: ["dessert"],
			cuisineType: ["American"],
			dishType: ["pudding", "dessert"],
			allergens: [],
			nutritionalInfo: {
				calories: 280,
				fiber: 6,
				protein: 6,
				carbs: 35,
				fat: 12,
			},
			ingredients: [
				{ name: "chia seeds", quantity: "3", unit: "tbsp" },
				{ name: "coconut milk", quantity: "1", unit: "cup" },
				{ name: "vanilla extract", quantity: "1/2", unit: "tsp" },
				{ name: "maple syrup (optional)", quantity: "1", unit: "tbsp" },
				{ name: "fresh fruit (for topping)", quantity: "1/2", unit: "cup" },
			],
			instructions: [
				"In a jar or bowl, combine chia seeds, coconut milk, vanilla extract, and maple syrup (if using). Stir well.",
				"Allow the mixture to rest for 5 minutes, then stir again to break up any clumps.",
				"Cover and refrigerate for at least 4 hours or overnight, until a pudding-like consistency forms.",
				"Top with fresh fruit, granola, or shredded coconut if desired.",
				"Serve chilled as a light dessert or snack.",
			],
			tags: ["chia pudding", "coconut", "dessert"],
		},
	];
